---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: Esaminare queste limitazioni di NetApp Backup and Recovery prima di utilizzare Backup and Recovery nel proprio ambiente. 
---
= Limitazioni note con NetApp Backup e ripristino per carichi di lavoro Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esamina le limitazioni attuali e le soluzioni alternative per i carichi di lavoro Kubernetes in NetApp Backup e ripristino.



[[limitation-in-the-backup-and-recovery-preview-for-netapp-console-local-deployment]]
== Limitazione nell'anteprima di Backup e ripristino per la distribuzione locale di NetApp Console

Nella versione di anteprima di Backup and Recovery per la distribuzione locale di NetApp Console, i backup su storage a oggetti sono supportati solo per le destinazioni ONTAP S3 e StorageGRID. L'archiviazione dei backup non è supportata in questa versione di anteprima.



[[changing-the-protection-policy-for-an-application]]
== Modifica della policy di protezione per un'applicazione

Se cambi la policy di protezione di un'applicazione per utilizzare un bucket diverso o una destinazione di replica secondaria, la protezione può non riuscire.

*Soluzione alternativa*: rimuovi l'applicazione e aggiungila di nuovo.



[[3-2-1-protection-policy-configuration-limitation]]
== Limitazione della configurazione della policy di protezione 3-2-1

Se crei una policy di protezione 3-2-1 che pianifica i backup su storage a oggetti separatamente dalla replica su storage secondario, la protezione può bloccarsi.

*Soluzione alternativa*: rimuovi l'applicazione e aggiungila di nuovo, poi proteggila con una policy di protezione diversa.
