---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Questa versione di NetApp Backup and Recovery presenta le seguenti limitazioni note. 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Qui sono elencate le piattaforme, i dispositivi o le funzionalità che non funzionano o non funzionano bene con questa versione.  Leggere attentamente queste limitazioni.

Le seguenti azioni e configurazioni non sono supportate nella versione di anteprima privata dei carichi di lavoro KVM in NetApp Backup and Recovery:



== Azioni non supportate

Le seguenti azioni non sono supportate nella versione di anteprima privata:

* Clona, monta o smonta le VM
* Ripristinare le VM in una posizione alternativa
* Proteggere le VM archiviate su SAN
* Proteggere le applicazioni
* Modifica gruppi di protezione
* Creare gruppi di protezione utilizzando VM da più host KVM
* Crea backup definiti dall'utente (sono supportati solo i backup avviati dalla NetApp Console )




== Configurazioni non supportate

Le seguenti configurazioni non sono supportate:

* Controllo degli accessi basato sui ruoli (RBAC)
* Dischi collegati direttamente all'host KVM
* Dischi distribuiti su più punti di montaggio o condivisioni NFS
* Formato disco RAW
* Tipi di pool di archiviazione diversi da NetFS (è supportato solo NetFS)




== Note sulla risoluzione dei problemi

Quando si utilizza l'anteprima privata dei carichi di lavoro KVM con NetApp Backup and Recovery, tenere presente quanto segue:

* Per garantire che i ripristini del carico di lavoro KVM vengano completati correttamente, accertarsi che l'impostazione *Abilita snapshot coerente con la VM* sia attiva nel criterio di protezione utilizzato per i backup KVM.
* Non è possibile eseguire il backup di un pool di archiviazione con host KVM gestiti da Apache CloudStack a meno che non si aggiungano tutti gli host gestiti a NetApp Backup and Recovery. Come soluzione alternativa, aggiungi ogni host KVM gestito da CloudStack a NetApp Backup and Recovery.
* Non è possibile eseguire il backup di una macchina virtuale arrestata che appartiene a un gruppo di protezione. Come soluzione alternativa, rimuovere la macchina virtuale arrestata dal gruppo di protezione prima di avviare il backup.

