---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Questa versione di NetApp Backup and Recovery presenta le seguenti limitazioni note. 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Qui sono elencate le piattaforme, i dispositivi o le funzionalità che non funzionano o non funzionano bene con questa versione.  Leggere attentamente queste limitazioni.

Le seguenti azioni e configurazioni non sono supportate nella versione di anteprima privata dei carichi di lavoro KVM in NetApp Backup and Recovery:



== Azioni non supportate

Le seguenti azioni non sono supportate nella versione di anteprima privata:

* Clona, monta o smonta le VM
* Ripristinare le VM in una posizione alternativa
* Proteggere le VM archiviate su SAN
* Proteggi le applicazioni
* Modifica gruppi di protezione
* Creare gruppi di protezione utilizzando VM da più host KVM
* Crea backup definiti dall'utente (sono supportati solo i backup avviati dalla console NetApp )




== Configurazioni non supportate

Le seguenti configurazioni non sono supportate:

* Controllo degli accessi basato sui ruoli (RBAC)
* Dischi collegati direttamente all'host KVM
* Dischi distribuiti su più punti di montaggio o condivisioni NFS
* Formato disco RAW
* Tipi di pool di archiviazione diversi da NetFS (è supportato solo NetFS)




== Account NetApp Console legacy non supportati

Gli account NetApp Console legacy non supportano le funzionalità richieste per proteggere i carichi di lavoro KVM.  Controlla se stai utilizzando un account legacy nell'interfaccia utente web della console.  Se si dispone di un account Console legacy, creare un nuovo account prima di proteggere i carichi di lavoro KVM.

.Passi
. Dal menu NetApp Console, selezionare *Amministrazione > Identità e accesso*.
. In *Organizzazione*, controlla se accanto all'ID organizzazione è visualizzato un *ID account*.
+
Se viene visualizzato un *ID account*, significa che stai utilizzando un account legacy.

. Se stai utilizzando un account legacy, procedi come segue:
+
.. Disconnettersi dalla Console e quindi accedere a https://console.netapp.com/["Pagina di accesso alla console"^] .
.. Seleziona *Iscriviti* per creare un nuovo account.



