---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Microsoft SQL Server database, SAP HANA database 
summary: 'Per poter utilizzare il servizio, NetApp Backup and Recovery deve prima rilevare i dati.  Durante l"individuazione, NetApp Backup and Recovery analizza tutti i volumi e i file nei sistemi all"interno della tua organizzazione.' 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Qui sono elencate le piattaforme, i dispositivi o le funzionalità che non funzionano o non funzionano bene con questa versione.  Leggere attentamente queste limitazioni.



[[backup-and-recovery-preview-for-netapp-console-local-deployment-limitation]]
== Anteprima di Backup and Recovery per la limitazione della distribuzione locale della NetApp Console

Nella versione di anteprima di Backup and Recovery per la distribuzione locale di NetApp Console, i backup su storage a oggetti sono supportati solo per le destinazioni ONTAP S3 e StorageGRID. L'archiviazione dei backup non è supportata in questa versione di anteprima.



[[clone-lifecycle-support]]
== Supporto del ciclo di vita dei cloni

* La clonazione da un archivio di oggetti non è supportata.
* Le operazioni di clonazione in blocco non sono supportate per i cloni su richiesta.
* La scelta dei gruppi I non è supportata.
* La scelta delle opzioni QOS (throughput massimo) non è supportata.




[[standard-deployment-mode-only]]
== Solo modalità di distribuzione standard

Questa versione NetApp Backup and Recovery funziona solo in modalità di distribuzione standard, non in modalità riservata o privata.



[[windows-cluster-name-restriction]]
== Restrizione del nome del cluster Windows

Il nome del cluster Windows non può contenere un carattere di sottolineatura (_).



[[snapcenter-migration-issues]]
== Problemi di migrazione SnapCenter

La migrazione delle risorse da SnapCenter a NetApp Backup and Recovery presenta le seguenti limitazioni.

Per i dettagli su come i criteri di SnapCenter migrano ai criteri di NetApp Backup and Recovery , vederelink:reference-policy-differences-snapcenter.html["Criteri in SnapCenter confrontati con quelli in NetApp Backup and Recovery"] .



[[resource-group-limitations]]
=== Limitazioni del gruppo di risorse

Se tutte le risorse in un gruppo di risorse sono protette e una di queste risorse è protetta anche all'esterno del gruppo di risorse, la migrazione da SnapCenter viene bloccata.

*Soluzione alternativa*: proteggere la risorsa in un gruppo di risorse o da sola, ma non in entrambi.



[[resources-with-multiple-policies-using-the-same-schedule-tier-not-supported]]
=== Risorse con più policy che utilizzano lo stesso livello di pianificazione non supportate

Non è possibile assegnare più policy che utilizzano lo stesso livello di pianificazione (ad esempio, oraria, giornaliera, settimanale, ecc.) a una risorsa.  NetApp Backup and Recovery non importerà tali risorse da SnapCenter.

*Soluzione alternativa*: associare a una risorsa solo un criterio utilizzando lo stesso livello di pianificazione.



[[hourly-policies-must-begin-at-the-start-of-the-hour]]
=== Le politiche orarie devono iniziare all'inizio dell'ora

Se si dispone di una policy SnapCenter che si ripete ogni ora ma non utilizza intervalli all'inizio dell'ora, NetApp Backup and Recovery non importerà la risorsa.  Ad esempio, le policy con orari 1:30, 2:30, 3:30, ecc. non sono supportate, mentre sono supportate le policy con orari 1:00, 2:00, 3:00, ecc.

*Soluzione alternativa*: utilizzare un criterio che si ripete a intervalli di 1 ora a partire dall'inizio dell'ora.



[[both-daily-and-monthly-policies-attached-to-one-resource-not-supported]]
=== Non sono supportate le policy giornaliere e mensili associate a una risorsa

Se una policy SnapCenter si ripete sia a intervalli giornalieri che mensili, NetApp Backup and Recovery non importerà la policy.

Ad esempio, non è possibile associare una policy giornaliera (con durata inferiore o uguale a 7 giorni o superiore a 7 giorni) a una risorsa e allo stesso tempo associare una policy mensile alla stessa risorsa.

*Soluzione alternativa*: utilizzare un criterio che preveda un intervallo giornaliero o mensile, ma non entrambi.



[[on-demand-backup-policies-not-migrated]]
=== Criteri di backup su richiesta non migrati

NetApp Backup and Recovery non importa policy di backup su richiesta da SnapCenter.



[[log-only-backup-policies-not-migrated]]
=== Criteri di backup solo log non migrati

NetApp Backup and Recovery non importa i criteri di backup solo log da SnapCenter.  Se una policy SnapCenter include backup solo di log, NetApp Backup and Recovery non importerà la risorsa.

*Soluzione alternativa*: utilizzare un criterio in SnapCenter che utilizzi più dei semplici backup di log.



[[host-mapping]]
=== Mappatura host

SnapCenter non mappa cluster di storage o storage VM per le risorse agli host, ma NetApp Backup and Recovery lo fa. Il cluster ONTAP on-premises o la storage VM non verranno mappati a un host nelle versioni di anteprima di NetApp Backup and Recovery. Inoltre, NetApp Console non supporta le storage VM.

*Soluzione alternativa*: prima di importare risorse da SnapCenter, creare un sistema in NetApp Backup and Recovery per tutti i sistemi di storage ONTAP locali registrati in SnapCenter locali.  Quindi, importare le risorse per quel cluster da SnapCenter in NetApp Backup and Recovery.



[[schedules-not-in-15-minute-intervals]]
=== Orari non a intervalli di 15 minuti

Se si dispone di una pianificazione di policy SnapCenter che inizia a una determinata ora e si ripete a intervalli diversi da 15 minuti, NetApp Backup and Recovery non importerà la pianificazione.

*Soluzione alternativa*: utilizzare SnapCenter per modificare il criterio in modo che venga ripetuto a intervalli di 15 minuti.
