---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: 'Per poter utilizzare il servizio, NetApp Backup and Recovery deve prima rilevare i dati.  Durante l"individuazione, NetApp Backup and Recovery analizza tutti i volumi e i file nei sistemi all"interno della tua organizzazione.' 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Qui sono elencate le piattaforme, i dispositivi o le funzionalità che non funzionano o non funzionano bene con questa versione.  Leggere attentamente queste limitazioni.



== Azioni non supportate

Le seguenti azioni non sono supportate nella versione di anteprima privata dei carichi di lavoro Hyper-V in NetApp Backup and Recovery:

* Creare gruppi di risorse
* Spanning dei dischi (su più condivisioni CIFS)
* Proteggere le VM su SAN
* Ripristina dall'archivio oggetti
* Proteggere gli host Hyper-V in cluster tramite System Center Virtual Machine Manager (SCVMM)




== Account NetApp Console legacy non supportati

Gli account legacy della console NetApp non supportano le funzionalità richieste per proteggere i carichi di lavoro Hyper-V.  Controlla se stai utilizzando un account legacy nell'interfaccia utente web della console.  Se si dispone di un account Console legacy, creare un nuovo account prima di proteggere i carichi di lavoro Hyper-V.

.Passi
. Dal menu NetApp Console, selezionare *Amministrazione > Identità e accesso*.
. In *Organizzazione*, controlla se accanto all'ID organizzazione è visualizzato un *ID account*.
+
Se viene visualizzato un *ID account*, significa che stai utilizzando un account legacy.

. Se stai utilizzando un account legacy, procedi come segue:
+
.. Disconnettersi dalla Console e quindi accedere a https://console.netapp.com/["Pagina di accesso alla console"^] .
.. Seleziona *Iscriviti* per creare un nuovo account.



