---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Questa versione di NetApp Backup and Recovery presenta le seguenti limitazioni note. 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esamina le limitazioni attuali per i carichi di lavoro KVM in NetApp Backup e ripristino.

Le seguenti azioni e configurazioni non supportate si applicano ai carichi di lavoro KVM in NetApp Backup e ripristino:



[[unsupported-actions]]
== Azioni non supportate

Le seguenti azioni non sono supportate:

* Nella versione di anteprima di Backup and Recovery per la distribuzione locale di NetApp Console, i backup su storage a oggetti sono supportati solo per le destinazioni ONTAP S3 e StorageGRID. L'archiviazione dei backup non è supportata in questa versione di anteprima.
* Clona, monta o smonta le VM
* Proteggere le VM archiviate su SAN
* Proteggere le applicazioni
* Crea backup definiti dall'utente (sono supportati solo i backup avviati dalla NetApp Console )




[[unsupported-configurations]]
== Configurazioni non supportate

Le seguenti configurazioni non sono supportate:

* Controllo degli accessi basato sui ruoli (RBAC)
* Dischi collegati direttamente all'host KVM
* Dischi distribuiti su più punti di montaggio o condivisioni NFS
* Formato disco RAW
* Tipi di pool di archiviazione diversi da NetFS (è supportato solo NetFS)




[[troubleshooting-notes]]
== Note sulla risoluzione dei problemi

Tieni presente quanto segue quando usi carichi di lavoro KVM con NetApp Backup e ripristino.

* I backup possono non riuscire se l'agente guest di QEMU non è in esecuzione in una macchina virtuale protetta. Per evitare questo problema, assicurati che il  `qemu-guest-agent` demone sia in esecuzione sulla macchina virtuale prima di avviare il backup.

