---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Questa versione di NetApp Backup and Recovery presenta le seguenti limitazioni note. 
---
= Limitazioni note con NetApp Backup and Recovery per carichi di lavoro KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Qui sono elencate le piattaforme, i dispositivi o le funzionalità che non funzionano o non funzionano bene con questa versione.  Leggere attentamente queste limitazioni.

Le seguenti azioni e configurazioni non sono supportate nei carichi di lavoro KVM in NetApp Backup and Recovery:



== Azioni non supportate

Le seguenti azioni non sono supportate:

* Clona, monta o smonta le VM
* Ripristinare le VM in una posizione alternativa
* Proteggere le VM archiviate su SAN
* Proteggere le applicazioni
* Crea backup definiti dall'utente (sono supportati solo i backup avviati dalla NetApp Console )




== Configurazioni non supportate

Le seguenti configurazioni non sono supportate:

* Controllo degli accessi basato sui ruoli (RBAC)
* Dischi collegati direttamente all'host KVM
* Dischi distribuiti su più punti di montaggio o condivisioni NFS
* Formato disco RAW
* Tipi di pool di archiviazione diversi da NetFS (è supportato solo NetFS)




== Note sulla risoluzione dei problemi

Tenere presente quanto segue quando si utilizzano carichi di lavoro KVM con NetApp Backup and Recovery.

* I backup possono fallire se l'agente guest QEMU non è in esecuzione in una VM protetta. Come soluzione alternativa, assicurarsi che il `qemu-guest-agent` demone sia in esecuzione sulla VM prima di avviare il backup.

