---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery deve prima rilevare i carichi di lavoro per consentirti di proteggerli. 
---
= Scopri i carichi di lavoro di Oracle Database in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'individuazione dei database Oracle consente a NetApp Backup and Recovery di proteggerli creando e ripristinando backup e snapshot.

*Ruolo di console obbligatorio* Super amministratore di backup e ripristino.  Scopri di piùlink:reference-roles.html["Ruoli e privilegi di backup e ripristino"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .



== Aggiungi un host database Oracle e scopri le risorse

Aggiungi le informazioni sull'host Oracle e lascia che NetApp Backup and Recovery rilevi i carichi di lavoro. All'interno di ciascun agente della console, seleziona i sistemi in cui desideri rilevare i carichi di lavoro.

.Passi
. Dal menu NetApp Console , selezionare *Protezione > Backup e ripristino*.
. In *Carichi di lavoro*, seleziona il riquadro *Oracle*.
. Seleziona *Scopri risorse*.
. Selezionare *Oracle* per il campo *Workload type*.
. Se non hai ancora memorizzato le credenziali per questo host di database Oracle, seleziona *Aggiungi credenziali*.
+
.. Selezionare l'agente della console da utilizzare con questo host.
.. Inserisci un nome per questa credenziale.
.. Inserisci il nome utente e la password per l'account.
.. Selezionare *Fatto*.


. *Registrazione host*: Aggiungere un nuovo host Oracle Database. Nel campo *FQDN o indirizzo IP dell'host*, immettere l'FQDN o l'indirizzo IP dell'host - per i database clusterizzati è possibile immettere l'FQDN o l'IP di qualsiasi nodo del cluster. Quindi fornire le credenziali, l'agente della Console e il numero di porta.
. (Facoltativo) Se si scelgono le credenziali per un utente non root, eseguire le seguenti operazioni:
+
.. Per istruzioni su come aggiungere l'utente non root selezionato al file sudoers sull'host del database Oracle, selezionare *Configure sudoers*.
.. Seguire le istruzioni nella finestra di dialogo, abilitare la casella di controllo al termine e selezionare *Fine*.


. *Impostazioni avanzate*: Eseguire le seguenti operazioni:
+
.. Inserisci la porta e il percorso di installazione da utilizzare per il NetApp plug-in. Il plug-in consente la comunicazione tra l'host del database Oracle e NetApp Backup and Recovery.
.. Scegli se consentire a NetApp Backup and Recovery di installare automaticamente il plug-in su ciascun host oppure se saltare l'installazione automatica del plug-in per tutti gli host. Seleziona *Mostrami come* per le istruzioni di installazione manuale.
+
[NOTE]
====
Backup and Recovery si connette a ciascun host tramite SSH per installare automaticamente il plug-in. Abilita *Usa installazione manuale* quando si verifica una delle seguenti condizioni:

*** Uno o più host non eseguono il servizio SSH.
*** Qualsiasi host dispone già del NetApp plug-in (anche se solo alcuni membri del cluster lo possiedono).
*** Preferisci installare il plug-in su ciascun host manualmente.


====
.. Se l'host del database è in cluster, abilita l'opzione *Aggiungi tutti gli host del cluster* per individuare tutti gli host presenti nel cluster.
.. Scegli se eseguire i controlli preliminari su ciascun host prima di installare automaticamente il plug-in. Se i controlli falliscono, l'installazione automatica del plug-in si interrompe. Per ignorare i controlli e installare comunque, abilita *Salta i controlli preliminari facoltativi* (attivata automaticamente se scegli l'installazione manuale).


. Seleziona *Scopri*.
+

TIP: L'aggiunta delle risorse può richiedere diversi minuti. Per visualizzare l'avanzamento, seleziona *Track progress* nella finestra di dialogo di stato in fondo alla pagina Inventario oppure seleziona *Monitoring* dal menu a sinistra.



.Risultato
Il carico di lavoro del database Oracle viene visualizzato nell'elenco dei carichi di lavoro nella pagina Inventory.



== Continua alla dashboard NetApp Backup and Recovery

. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Selezionare un riquadro del carico di lavoro (ad esempio, Microsoft SQL Server).
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

