---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery deve rilevare le macchine virtuali Hyper-V prima di poterle proteggere. 
---
= Scopri i carichi di lavoro Hyper-V in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery deve rilevare le macchine virtuali Hyper-V prima di poterle proteggere.

*Ruolo di console obbligatorio* Super amministratore di backup e ripristino. Scopri di piùlink:reference-roles.html["Ruoli e privilegi di backup e ripristino"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso alla console NetApp per tutti i servizi"^] .



== Aggiungi un host Hyper-V e scopri le risorse

Aggiungi le informazioni sull'host Hyper-V e lascia che NetApp Backup and Recovery rilevi le macchine virtuali.  All'interno di ciascun agente della Console, seleziona i sistemi in cui desideri scoprire le risorse.


NOTE: Quando si aggiungono host Hyper-V e si individuano risorse, NetApp Backup and Recovery installa il plug-in NetApp Hyper-V e il plug-in NetApp SnapCenter Windows FileSystem sull'host Hyper-V per facilitare la gestione e la protezione delle macchine virtuali.

.Passi
. Dal menu della console NetApp , selezionare *Protezione* > *Backup e ripristino*.
+
Se è la prima volta che accedi a NetApp Backup and Recovery, hai già un sistema nella Console ma non hai ancora individuato alcuna risorsa, viene visualizzata la pagina di destinazione "Benvenuti nel nuovo NetApp Backup and Recovery" che mostra un'opzione per *Individuare risorse*.

. Seleziona *Scopri risorse*.
. Inserisci le seguenti informazioni:
+
.. *Tipo di carico di lavoro*: selezionare *Hyper-V*.
.. Se non hai ancora memorizzato le credenziali per questo host Hyper-V, seleziona *Aggiungi credenziali*.
+
... Selezionare l'agente della console da utilizzare con questo host.
... Inserisci un nome per questa credenziale.
... Inserisci il nome utente e la password per l'account.
... Selezionare *Fatto*.


.. *Registrazione host*: aggiungi un nuovo host Hyper-V.  Immettere l'FQDN o l'indirizzo IP dell'host, le credenziali, l'agente della console e il numero di porta.


. Seleziona *Scopri*.
+

TIP: Questo processo potrebbe richiedere alcuni minuti.



.Risultato
Dopo che NetApp Backup and Recovery rileva le risorse, la pagina Inventario visualizza il carico di lavoro Hyper-V nell'elenco dei carichi di lavoro.



== Continua alla dashboard di NetApp Backup and Recovery

.Passi
. Per visualizzare la dashboard NetApp Backup and Recovery, dal menu NetApp Console, selezionare *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

