---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: Per poter utilizzare il servizio, NetApp Backup and Recovery deve prima rilevare i carichi di lavoro. 
---
= Scopri i carichi di lavoro Kubernetes in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri i cluster Kubernetes e i relativi carichi di lavoro in NetApp Backup and Recovery, così da poterli proteggere con policy di protezione.

*Ruolo richiesto NetApp Console* Super admin di Backup and Recovery. Se stai proteggendo dati archiviati su un cluster Cloud Volumes ONTAP, è richiesto anche il ruolo Cloud Volumes ONTAP Admin. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].



[[discover-kubernetes-workloads]]
== Scopri i carichi di lavoro di Kubernetes

Nell'inventario di Backup and Recovery, puoi individuare i cluster e i carichi di lavoro Kubernetes nel tuo ambiente. Aggiungendo un cluster puoi registrarlo in NetApp Backup and Recovery e scoprire le sue applicazioni e risorse da proteggere. Puoi anche individuare le risorse Kubernetes locali isolate dalla rete usando la distribuzione locale di NetApp Console.

[NOTE]
====
Quando scopri un cluster attualmente protetto con Trident Protect, tutte le pianificazioni di backup utilizzate con Trident Protect vengono disabilitate durante il processo di rilevamento, poiché le pianificazioni di backup di Trident Protect non sono compatibili con NetApp Backup and Recovery. Per proteggere le applicazioni del cluster, link:br-use-policies-create.html["crea una nuova policy di protezione"] oppure associa le applicazioni a una policy esistente. Puoi quindi rimuovere le pianificazioni di backup di Trident Protect, se necessario.

====
.Passi
. Eseguire una delle seguenti operazioni:
+
** Se stai rilevando carichi di lavoro Kubernetes per la prima volta, in NetApp Backup and Recovery, in *Carichi di lavoro*, seleziona il riquadro *Kubernetes*.
** Se hai già individuato i carichi di lavoro Kubernetes, in NetApp Backup and Recovery seleziona *Inventario* > *Carichi di lavoro* e quindi seleziona *Individuazione risorse*.


. Selezionare il tipo di carico di lavoro *Kubernetes*.
. Inserisci un nome cluster e scegli un agente Console da usare con il cluster.
+
Backup and Recovery fornisce istruzioni che cambiano in base al tipo di installazione che scegli. Se usi la distribuzione locale di NetApp Console, puoi scegliere le istruzioni per individuare le risorse air-gapped che non hanno connettività di rete esterna.

. Scegli un tipo di installazione per visualizzare le istruzioni per installare Trident Protect sul tuo cluster Kubernetes:
+
** Seleziona *Connesso* per individuare i cluster che hanno connettività di rete esterna.
** Seleziona *Air-gapped* per individuare i cluster privi di connettività di rete esterna.
+
[role="tabbed-block"]
====
.Scoperta connessa
--
... Segui le istruzioni della riga di comando visualizzate in Backup and Recovery. Questi passaggi garantiscono che Backup and Recovery possa interagire con il cluster.


--
.Scoperta air-gapped
--
... Inserisci l'URL del tuo registro di container Docker privato. Questo registro viene utilizzato per scaricare le immagini di Trident Protect e Trident Protect Connector durante l'installazione.
... Se il tuo container registry privato richiede l'autenticazione, usa uno dei seguenti metodi per configurare le credenziali del registry:
+
**** *Autenticazione a livello di nodo*: configura le credenziali del registro nel runtime del container su ciascun nodo. Una volta configurato, tutti i pod possono scaricare le immagini senza richiedere ulteriori impostazioni Helm.
**** *Segreto per il pull dell'immagine Kubernetes*: Crea un segreto per il pull dell'immagine Kubernetes nel  `trident-protect` namespace, quindi fai riferimento ad esso durante la fase di upgrade di Helm nelle istruzioni di installazione di Trident Protect:
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Segui le istruzioni della riga di comando visualizzate in NetApp Backup and Recovery, aggiungendo le informazioni dell'image pull secret durante la fase Helm (se necessario). Questi passaggi garantiscono che NetApp Backup and Recovery possa interagire con il cluster.


--
====


. Dopo aver completato i passaggi di installazione di Trident Protect, seleziona *Scopri*.
+
Il cluster viene aggiunto all'inventario.

. Selezionare *Visualizza* nel carico di lavoro Kubernetes associato per visualizzare l'elenco di applicazioni, cluster e namespace per quel carico di lavoro.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continua alla dashboard NetApp Backup and Recovery

Segui questi passaggi per visualizzare la dashboard di NetApp Backup and Recovery e verificare le risorse rilevate.

. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Seleziona il riquadro del carico di lavoro Kubernetes.
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.
+
link:br-use-dashboard.html["Scopri cosa ti mostra la Dashboard"].


