---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery deve prima rilevare i carichi di lavoro per consentirti di proteggerli. 
---
= Scopri i carichi di lavoro KVM in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Individua gli host KVM e le macchine virtuali in NetApp Backup and Recovery così puoi proteggerli con criteri di protezione. Il tuo ambiente KVM deve essere gestito da una piattaforma di gestione come Apache CloudStack prima dell'individuazione.

*Ruolo di console obbligatorio* Super amministratore di backup e ripristino.  Scopri di piùlink:reference-roles.html["Ruoli e privilegi di backup e ripristino"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .



[[add-a-management-platform-kvm-host-and-discover-resources]]
== Aggiungi una piattaforma di gestione, un host KVM e scopri le risorse

Aggiungi informazioni sulla piattaforma di gestione e sull'host KVM e lascia che NetApp Backup and Recovery rilevi i carichi di lavoro.

.Passi
. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. In *Carichi di lavoro*, seleziona il riquadro *KVM*.
+
Se è la prima volta che accedi a NetApp Backup and Recovery e hai già un sistema nella Console ma nessuna risorsa rilevata, viene visualizzata la pagina "Benvenuto nel nuovo NetApp Backup and Recovery" con l'opzione *Rileva risorse*.

. Seleziona *Scopri risorse*.
. Inserisci le seguenti informazioni:
+
.. *Tipo di carico di lavoro*: selezionare *KVM*.
.. Se non hai ancora integrato la tua piattaforma di gestione con Backup e Ripristino, seleziona *Aggiungi piattaforma di gestione*.
+
... Inserisci le seguenti informazioni:
+
**** *Indirizzo IP o FQDN della piattaforma di gestione*: Inserisci l'indirizzo IP o un FQDN della piattaforma di gestione.
**** *Chiave API*: inserisci la chiave API da utilizzare per autenticare le richieste API.
**** *Chiave segreta*: inserisci la chiave segreta da utilizzare per autenticare le richieste API.
**** *Porta*: immettere la porta da utilizzare per la comunicazione tra Backup and Recovery e la piattaforma di gestione.
**** *Agenti*: selezionare un agente della console da utilizzare per facilitare la comunicazione tra Backup and Recovery e la piattaforma di gestione.


... Al termine, seleziona *Aggiungi*.


.. *Impostazioni KVM*: aggiungi un nuovo host KVM immettendo le seguenti informazioni:
+
*** *FQDN o indirizzo IP KVM*: immettere l'FQDN o l'indirizzo IP dell'host.
*** *Credenziali*: immettere il nome utente e la password per l'host KVM.
*** *Agente console*: seleziona l'agente console da utilizzare per la comunicazione tra Backup and Recovery e l'host KVM.
*** *Numero porta*: immettere la porta da utilizzare per la comunicazione tra Backup and Recovery e l'host KVM.
*** *Piattaforma di gestione*: se l'host KVM è gestito e hai aggiunto la piattaforma di gestione a Backup e ripristino, seleziona la piattaforma di gestione dall'elenco.




. Seleziona *Scopri*.
+

TIP: Questo processo potrebbe richiedere alcuni minuti.



.Risultato
Il carico di lavoro KVM viene visualizzato nell'elenco dei carichi di lavoro nella pagina Inventario.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continua alla dashboard NetApp Backup and Recovery

.Passi
. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Seleziona il riquadro del carico di lavoro KVM.
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

