---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: Per poter utilizzare il servizio, NetApp Backup and Recovery deve prima rilevare i carichi di lavoro. 
---
= Scopri i carichi di lavoro Kubernetes in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery deve rilevare i carichi di lavoro Kubernetes prima di proteggerli.

*Ruolo richiesto NetApp Console* Super admin di Backup and Recovery. Se stai proteggendo dati archiviati su un cluster Cloud Volumes ONTAP, è richiesto anche il ruolo Cloud Volumes ONTAP Admin. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].



[[discover-kubernetes-workloads]]
== Scopri i carichi di lavoro di Kubernetes

Nell'inventario di Backup and Recovery, scopri i carichi di lavoro Kubernetes nel tuo ambiente. Aggiungendo un carico di lavoro aggiungi un cluster Kubernetes a NetApp Backup and Recovery. Puoi quindi aggiungere applicazioni e proteggere le risorse del cluster. Puoi anche scoprire risorse Kubernetes locali isolate (air-gapped) usando la distribuzione locale di NetApp Console.

[NOTE]
====
Quando si rileva un cluster attualmente protetto con Trident Protect, tutte le pianificazioni di backup utilizzate con Trident Protect vengono disabilitate durante il processo di rilevamento (le pianificazioni di backup di Trident Protect non sono compatibili con Backup and Recovery). Per proteggere le applicazioni del cluster, link:br-use-policies-create.html["crea una nuova policy di protezione"] oppure associare le applicazioni a una policy esistente. È quindi possibile rimuovere le pianificazioni di backup di Trident Protect, se necessario.

====
.Passi
. Eseguire una delle seguenti operazioni:
+
** Se stai rilevando carichi di lavoro Kubernetes per la prima volta, in NetApp Backup and Recovery, in *Carichi di lavoro*, seleziona il riquadro *Kubernetes*.
** Se hai già individuato i carichi di lavoro Kubernetes, in NetApp Backup and Recovery seleziona *Inventario* > *Carichi di lavoro* e quindi seleziona *Individuazione risorse*.


. Selezionare il tipo di carico di lavoro *Kubernetes*.
. Inserisci un nome cluster e scegli un agente Console da usare con il cluster.
+
Backup and Recovery fornisce istruzioni che cambiano a seconda del tipo di installazione che scegli. Se usi la distribuzione locale di NetApp Console, puoi scegliere istruzioni che ti permettono di individuare risorse air-gapped senza connettività di rete esterna.

. Scegli un tipo di installazione per visualizzare le istruzioni per installare Trident Protect sul tuo cluster Kubernetes:
+
** Seleziona *Connesso* per individuare i cluster che hanno connettività di rete esterna.
** Seleziona *Air-gapped* per individuare i cluster privi di connettività di rete esterna.
+
[role="tabbed-block"]
====
.Scoperta connessa
--
... Segui le istruzioni della riga di comando visualizzate in Backup and Recovery. Questi passaggi garantiscono che Backup and Recovery possa interagire con il cluster.


--
.Scoperta air-gapped
--
... Inserisci l'URL del tuo registro di container Docker privato. Questo registro viene utilizzato per scaricare le immagini di Trident Protect e Trident Protect Connector durante l'installazione.
... Se il tuo container registry privato richiede l'autenticazione, usa uno dei seguenti metodi per configurare le credenziali del registry:
+
**** *Autenticazione a livello di nodo*: configura le credenziali del registro nel runtime del container su ciascun nodo. Una volta configurato, tutti i pod possono scaricare le immagini senza richiedere ulteriori impostazioni Helm.
**** *Segreto per il pull dell'immagine Kubernetes*: Crea un segreto per il pull dell'immagine Kubernetes nel  `trident-protect` namespace, quindi fai riferimento ad esso durante la fase di upgrade di Helm nelle istruzioni di installazione di Trident Protect:
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Segui le istruzioni della riga di comando visualizzate in NetApp Backup and Recovery, aggiungendo le informazioni dell'image pull secret durante la fase Helm (se necessario). Questi passaggi garantiscono che NetApp Backup and Recovery possa interagire con il cluster.


--
====


. Dopo aver completato i passaggi di installazione di Trident Protect, seleziona *Scopri*.
+
Il cluster viene aggiunto all'inventario.

. Selezionare *Visualizza* nel carico di lavoro Kubernetes associato per visualizzare l'elenco di applicazioni, cluster e namespace per quel carico di lavoro.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continua alla dashboard NetApp Backup and Recovery

Per visualizzare la dashboard NetApp Backup and Recovery , seguire questi passaggi.

. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Seleziona il riquadro del carico di lavoro Kubernetes.
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.
+
link:br-use-dashboard.html["Scopri cosa ti mostra la Dashboard"].


