---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery deve prima rilevare i carichi di lavoro per consentirti di proteggerli. 
---
= Scopri i carichi di lavoro di Oracle Database in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery deve prima rilevare i database Oracle per poterli proteggere.

*Ruolo di console obbligatorio* Super amministratore di backup e ripristino.  Scopri di piùlink:reference-roles.html["Ruoli e privilegi di backup e ripristino"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .



== Aggiungi un host Oracle e scopri le risorse

Aggiungi le informazioni sull'host Oracle e lascia che NetApp Backup and Recovery rilevi i carichi di lavoro. All'interno di ciascun agente della console, seleziona i sistemi in cui desideri rilevare i carichi di lavoro.

.Passi
. Dal menu NetApp Console , selezionare *Protezione > Backup e ripristino*.
. In *Carichi di lavoro*, seleziona il riquadro *Oracle*.
+
Se si accede a Backup and Recovery per la prima volta e si ha un sistema nella Console ma non sono state rilevate risorse, viene visualizzata la pagina _Benvenuti nel nuovo NetApp Backup and Recovery_ con l'opzione *Rileva risorse*.

. Seleziona *Scopri risorse*.
. Inserisci le seguenti informazioni:
+
.. *Tipo di carico di lavoro*: seleziona *Oracle*.
.. Se non hai ancora memorizzato le credenziali per questo host Oracle, seleziona *Aggiungi credenziali*.
+
... Selezionare l'agente della console da utilizzare con questo host.
... Inserisci un nome per questa credenziale.
... Inserisci il nome utente e la password per l'account.
... Selezionare *Fatto*.


.. *Registrazione host*: aggiungi un nuovo host Oracle.  Immettere l'FQDN o l'indirizzo IP dell'host, le credenziali, l'agente della console e il numero di porta.


. Seleziona *Scopri*.
+

TIP: Questo processo potrebbe richiedere alcuni minuti.



.Risultato
Il carico di lavoro Oracle viene visualizzato nell'elenco dei carichi di lavoro nella pagina Inventario.



== Continua alla dashboard NetApp Backup and Recovery

. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Selezionare un riquadro del carico di lavoro (ad esempio, Microsoft SQL Server).
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

