---
sidebar: sidebar 
permalink: br-start-discover-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect 
summary: NetApp Backup and Recovery deve rilevare le macchine virtuali Hyper-V prima di poterle proteggere. 
---
= Scopri i carichi di lavoro Hyper-V in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le macchine virtuali Hyper-V in NetApp Backup and Recovery così puoi proteggerle con criteri di protezione.

*Ruolo richiesto nella Console* Backup and Recovery super admin. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].



[[add-a-hyper-v-host-and-discover-resources]]
== Aggiungi un host Hyper-V e scopri le risorse

Aggiungi le informazioni sull'host Hyper-V per consentire a NetApp Backup and Recovery di individuare le macchine virtuali. In ogni agente della Console, seleziona i sistemi in cui vuoi individuare le risorse.


NOTE: Quando si aggiungono host Hyper-V e si individuano risorse, NetApp Backup and Recovery installa il plug-in NetApp Hyper-V e il plug-in NetApp SnapCenter Windows FileSystem sull'host Hyper-V per facilitare la gestione e la protezione delle macchine virtuali.

.Passi
. Dal menu NetApp Console, seleziona *Protezione* > *Backup and Recovery*.
+
Se è la prima volta che accedi a NetApp Backup and Recovery e hai già un sistema nella Console ma non hai ancora scoperto le risorse, viene visualizzata la landing page "Welcome to the new NetApp Backup and Recovery" con l'opzione *Scopri risorse*.

. Seleziona *Scopri risorse*.
. Inserisci le seguenti informazioni:
+
.. *Tipo di carico di lavoro*: selezionare *Hyper-V*.
.. Se non hai ancora memorizzato le credenziali per questo host Hyper-V, seleziona *Aggiungi credenziali*.
+
... Selezionare l'agente della console da utilizzare con questo host.
... Inserisci un nome per questa credenziale.
... Inserisci il nome utente e la password per l'account.
... Selezionare *Fatto*.


.. *Registrazione host*: aggiungi un nuovo host Hyper-V immettendo l'FQDN o l'indirizzo IP dell'host, le credenziali, l'agente della console e il numero di porta. Se l'FQDN non è risolvibile dall'agente della console, utilizzare invece l'indirizzo IP. Per i cluster FCI, immettere l'indirizzo IP di gestione del cluster FCI.


. Seleziona *Scopri*.
+

TIP: Questo processo potrebbe richiedere alcuni minuti.



.Risultato
Dopo che NetApp Backup and Recovery rileva le risorse, la pagina Inventario visualizza il carico di lavoro Hyper-V nell'elenco dei carichi di lavoro.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continua alla dashboard NetApp Backup and Recovery

.Passi
. Dal menu NetApp Console, seleziona *Protezione* > *Backup and Recovery*.
. Seleziona il riquadro del carico di lavoro Hyper-V.
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

