---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: Questa sezione FAQ può aiutarti se stai cercando una risposta rapida a una domanda. 
---
= Domande frequenti su NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Questa sezione FAQ può aiutarti se stai cercando una risposta rapida a una domanda.



== Distribuzione

*È necessaria una licenza per utilizzare la versione di anteprima NetApp Backup and Recovery ?*

È possibile utilizzare i seguenti tipi di licenza:

* Registrati per una prova gratuita di 30 giorni.


*Come si abilita NetApp Backup and Recovery?*  NetApp Backup and Recovery non richiede alcuna abilitazione.  L'opzione di backup e ripristino viene abilitata automaticamente nella barra di navigazione a sinistra della Console.

Per iniziare, è necessario registrarsi o contattare il proprio rappresentante commerciale NetApp per provare Backup and Recovery.  Quindi, quando si utilizza l'agente Console, questo includerà le funzionalità appropriate per il servizio.

Per iniziare a utilizzare NetApp Backup and Recovery, seleziona "Inizia a scoprire i carichi di lavoro" dalla pagina di destinazione iniziale.

* NetApp Backup and Recovery è disponibile nelle modalità standard, limitata e privata?*  Al momento, NetApp Backup and Recovery è disponibile solo in modalità standard. Restate sintonizzati per saperne di più.

Per una spiegazione su queste modalità in tutti i servizi dati NetApp , fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"^] .



== Accesso

*Qual è l'URL NetApp Backup and Recovery ?*  Per l'URL, in un browser, inserisci: https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^] per accedere alla NetApp Console.

*Come vengono gestiti i permessi di accesso?* Solo gli amministratori dell'organizzazione hanno la possibilità di avviare il servizio e individuare i carichi di lavoro (perché ciò implica l'impegno nell'utilizzo di una risorsa).  Le interazioni successive possono essere eseguite da qualsiasi ruolo.

*Qual è la risoluzione migliore per il tuo dispositivo?* La risoluzione del dispositivo consigliata per NetApp Backup and Recovery è 1920x1080 o superiore.

*Quale browser dovrei usare?* Qualsiasi browser moderno funzionerà.



== Interazione con altri servizi

* NetApp Backup and Recovery è a conoscenza delle impostazioni di protezione effettuate in NetApp ONTAP?*  Sì, NetApp Backup and Recovery rileva le pianificazioni degli snapshot impostate in ONTAP.

*Se imposti una policy utilizzando NetApp Backup and Recovery, devi apportare modifiche future solo in Backup and Recovery?*  Ti consigliamo di apportare modifiche ai criteri da NetApp Backup and Recovery.



== Carichi di lavoro

*Da cosa è costituito un carico di lavoro?* Un carico di lavoro è un'applicazione per la versione Preview 2025. Un carico di lavoro include tutti i volumi utilizzati da una singola istanza dell'applicazione.  Ad esempio, un'istanza di database Microsoft SQL Server distribuita su mssql3.host.com può avere rispettivamente vol1 e vol2 per i suoi dati e log.  Questi volumi insieme costituiscono il carico di lavoro per quella specifica istanza del database.

*Quali carichi di lavoro supporta NetApp Backup and Recovery ?*

Per la versione Preview 2025, NetApp Backup and Recovery è in grado di identificare i seguenti carichi di lavoro: applicazioni Microsoft SQL Server.

*Cos'è un carico di lavoro "protetto"?* In NetApp Backup and Recovery, un carico di lavoro mostra uno stato "protetto" quando è abilitata una policy di rilevamento primaria.

*Che cosa si intende per carico di lavoro "a rischio"?* Se un carico di lavoro non ha un criterio di rilevamento primario abilitato, è "a rischio" anche se ha un criterio di backup e snapshot abilitato.

*Nuovo carico di lavoro aggiunto, ma non ancora visualizzato* Se hai aggiunto un nuovo carico di lavoro al tuo ambiente, avvia nuovamente l'individuazione e applica i criteri di protezione per proteggere la nuova risorsa.



== Politiche di protezione

* NetApp Backup and Recovery è a conoscenza delle impostazioni di protezione effettuate in NetApp ONTAP?*

Sì, NetApp Backup and Recovery rileva le pianificazioni degli snapshot impostate in ONTAP e verifica se ARP e FPolicy sono abilitati in un carico di lavoro rilevato. Le informazioni visualizzate inizialmente nella Dashboard sono aggregate da altre soluzioni e prodotti NetApp .

* NetApp Backup and Recovery è a conoscenza delle policy già definite in SnapCenter?*

Sì, se hai carichi di lavoro gestiti in SnapCenter, le policy gestite da tali prodotti vengono importate in NetApp Backup and Recovery.

*È possibile modificare le policy trasferite da SnapCenter?*

Sì, è possibile modificare i criteri gestiti da SnapCenter all'interno di NetApp Backup and Recovery.

*Se esistono policy da ONTAP (già abilitate in System Manager come ARP, FPolicy e snapshot), queste vengono modificate in NetApp Backup and Recovery?*

No. NetApp Backup and Recovery non modifica alcuna policy di rilevamento esistente (impostazioni ARP, FPolicy) da ONTAP.

*Cosa succede se aggiungi nuove policy in SnapCenter dopo esserti registrato a NetApp Backup and Recovery?*

NetApp Backup and Recovery riconosce tutte le nuove policy create in SnapCenter.

*È possibile modificare le politiche di ONTAP?*

Sì, è possibile modificare i criteri da ONTAP in NetApp Backup and Recovery.  È anche possibile creare nuove policy in NetApp Backup and Recovery e applicarle ai carichi di lavoro.  Questa azione sostituisce le policy ONTAP esistenti con le policy create in NetApp Backup and Recovery.
