---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: Licenza NetApp Backup and Recovery acquistando un abbonamento pay-as-you-go o annuale dal marketplace del tuo cloud provider, oppure acquistando una bring-your-own-license da NetApp. 
---
= Impostare la licenza per NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configura le licenze per NetApp Backup and Recovery in NetApp Console o NetApp Console nella distribuzione locale utilizzando un abbonamento marketplace o una licenza bring-your-own (BYOL) di NetApp. È necessaria una licenza valida per attivare il servizio, creare backup e ripristinare i dati nei sistemi di produzione.

Alcune note sul funzionamento delle licenze:

* Quando usi i carichi di lavoro ONTAP Volumes, puoi individuare e ripristinare i volumi senza una licenza. Tuttavia, se hai bisogno di proteggere (eseguire il backup) dei volumi, devi acquistare una licenza.
* Se usi Backup and Recovery con la distribuzione locale di NetApp Console, puoi acquistare solo una licenza bring-your-own-license (BYOL).
* La licenza BYOL (Bring Your Own License) NetApp Backup and Recovery è una licenza mobile che puoi utilizzare su tutti i sistemi associati alla tua organizzazione o al tuo account NetApp Console .  Pertanto, se si dispone di una capacità di backup sufficiente da una licenza BYOL esistente, non sarà necessario acquistare un'altra licenza BYOL.
* Se utilizzi una licenza BYOL con NetApp Console, ti consigliamo di sottoscrivere anche un abbonamento pay-as-you-go (PAYGO). Se esegui il backup di una quantità di dati superiore a quella consentita dalla tua licenza BYOL o se la durata della licenza scade, il backup continuerà tramite il tuo abbonamento pay-as-you-go (PAYGO), senza alcuna interruzione del servizio.
* Quando esegui il backup dei dati ONTAP locali su StorageGRID, ti serve una licenza BYOL, ma non c'è alcun costo per lo spazio di storage del cloud provider.


link:concept-backup-to-cloud.html["Scopri di più sui costi associati all'utilizzo di NetApp Backup and Recovery."]



[[licensing-options-for-netapp-backup-and-recovery]]
== Opzioni di licenza per NetApp Backup and Recovery

Hai tre opzioni di licenza per NetApp Backup and Recovery:

* Acquista una licenza diretta, nota anche come bring-your-own-license (BYOL), da NetApp. Questa opzione si applica sia a NetApp Console che alla distribuzione locale di Console.
* Acquista un contratto annuale da un marketplace di hyperscaler. Questa opzione si applica solo a NetApp Console.
* Abbonati a una licenza pay-as-you-go (PAYGO) da un marketplace di hyperscaler. Questa opzione si applica solo a NetApp Console.




[[30-day-free-trial]]
=== Prova gratuita di 30 giorni

È disponibile una prova gratuita di 30 giorni di NetApp Backup and Recovery per tutti i carichi di lavoro senza licenza, ad eccezione dei carichi di lavoro ONTAP Volumes. Puoi iniziare la prova quando inizi a usare un carico di lavoro, prima di scoprirne le risorse. Dopo che hai avviato la prova, il suo stato e la capacità utilizzata vengono visualizzati sotto *Free Trials* nella home page di NetApp Backup and Recovery.



==== Termina la prova gratuita

Puoi terminare la prova gratuita per un carico di lavoro in qualsiasi momento dalla pagina iniziale che viene visualizzata quando accedi a NetApp Backup and Recovery. Se vuoi continuare a usare NetApp Backup and Recovery dopo la fine della prova gratuita, devi configurare un abbonamento a pagamento nella sezione *Licenses and subscriptions* dell'interfaccia NetApp Console. Se non vuoi continuare a usare NetApp Backup and Recovery, puoi terminare la prova gratuita senza sottoscrivere un piano a pagamento. Puoi link:prev-ontap-backup-manage.html["annullare la registrazione NetApp Backup and Recovery dal sistema"] prima della fine della prova e non ti verrà addebitato nulla.

.Passi
. Dalla home page di NetApp Backup and Recovery, scegli la prova gratuita che vuoi terminare sotto *Free trials*.
. Seleziona *Termina prova gratuita*.
. Digitare *fine prova* nella casella.
. Seleziona *Termina prova* per confermare.




[[use-a-byol-license]]
=== Usa una licenza BYOL

Le licenze Bring-your-own di NetApp sono disponibili con durata di 1, 2 o 3 anni.  Si paga solo per i dati che si proteggono, calcolati in base alla capacità logica utilizzata (prima di qualsiasi efficienza) dei volumi ONTAP di origine sottoposti a backup.  Questa capacità è nota anche come Front-End Terabyte (FETB).

La licenza BYOL NetApp Backup and Recovery è una licenza mobile in cui la capacità totale è condivisa tra tutti i sistemi associati all'organizzazione o all'account NetApp Console .  Per i sistemi ONTAP , è possibile ottenere una stima approssimativa della capacità necessaria eseguendo il comando CLI `volume show -fields logical-used-by-afs` per i volumi di cui si intende eseguire il backup.

Se non disponi di una licenza BYOL per NetApp Backup and Recovery, seleziona l'icona della chat in basso a destra nella Console per acquistarne una.

Facoltativamente, se disponi di una licenza basata su nodi non assegnata per Cloud Volumes ONTAP che non utilizzerai, puoi convertirla in una licenza NetApp Backup and Recovery con lo stesso equivalente in dollari e la stessa data di scadenza. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Vai qui per i dettagli"^] .

Puoi usare NetApp Console o NetApp Console distribuzione locale per gestire le licenze BYOL. Puoi aggiungere nuove licenze, aggiornare quelle esistenti e visualizzare lo stato delle licenze dalla Console.

https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html["Scopri come aggiungere licenze"^].



[[use-a-marketplace-license-applies-to-netapp-console-only]]
=== Usa una licenza del marketplace (valido solo per NetApp Console)

Paga annualmente NetApp Backup and Recovery acquistando un contratto annuale.  Sono disponibili con durata di 1, 2 o 3 anni.

Se hai un contratto annuale da un marketplace, tutto il consumo di NetApp Backup and Recovery viene addebitato su quel contratto.

Quando si utilizza AWS, sono disponibili due contratti annuali da https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["Pagina AWS Marketplace"^] per i sistemi Cloud Volumes ONTAP e ONTAP on-premise:

* Un piano "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
+
Se vuoi utilizzare questa opzione, configura il tuo abbonamento dalla pagina Marketplace e poi https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["associa l'abbonamento alle tue credenziali AWS"^] .  Tieni presente che dovrai pagare anche i tuoi sistemi Cloud Volumes ONTAP utilizzando questo abbonamento contrattuale annuale, poiché puoi assegnare un solo abbonamento attivo alle tue credenziali AWS nella Console.

* Un piano "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Vedi il https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Argomento sulla licenza Cloud Volumes ONTAP"^] per saperne di più su questa opzione di licenza.

+
Se desideri utilizzare questa opzione, puoi impostare il contratto annuale quando crei un sistema Cloud Volumes ONTAP e la Console ti chiederà di iscriverti ad AWS Marketplace.



Quando usi Azure, ci sono due contratti annuali disponibili dal  https://marketplace.microsoft.com/en-us/product/netapp.netapp-bluexp["Pagina di Azure Marketplace"^] per Cloud Volumes ONTAP e i sistemi ONTAP on-premises:

* Un piano "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
+
Se vuoi utilizzare questa opzione, configura il tuo abbonamento dalla pagina Marketplace e poi https://docs.netapp.com/us-en/console-setup-admin/task-adding-azure-accounts.html#subscribe["associare la sottoscrizione alle credenziali di Azure"^] .  Tieni presente che dovrai pagare anche i tuoi sistemi Cloud Volumes ONTAP utilizzando questo abbonamento contrattuale annuale, poiché puoi assegnare un solo abbonamento attivo alle tue credenziali Azure nella Console.

* Un piano "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Vedi il https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Argomento sulla licenza Cloud Volumes ONTAP"^] per saperne di più su questa opzione di licenza.

+
Se si desidera utilizzare questa opzione, è possibile impostare il contratto annuale quando si crea un sistema Cloud Volumes ONTAP e la Console richiede di sottoscrivere l'abbonamento ad Azure Marketplace.



Se utilizzi GCP, contatta il tuo rappresentante commerciale NetApp per acquistare un contratto annuale.  Il contratto è disponibile come offerta privata su Google Cloud Marketplace.

Dopo che NetApp avrà condiviso con te l'offerta privata, potrai selezionare il piano annuale quando ti iscrivi da Google Cloud Marketplace durante l'attivazione NetApp Backup and Recovery .



[[use-a-netapp-backup-and-recovery-paygo-subscription-applies-to-netapp-console-only]]
=== Usa un abbonamento PAYGO NetApp Backup and Recovery (valido solo per NetApp Console)

Con il pay-as-you-go, paghi al tuo cloud provider i costi dello storage a oggetti e i costi di licenza di backup NetApp su base oraria con un unico abbonamento. Dovresti abbonarti a *NetApp Intelligent Services* nel Marketplace anche se hai una prova gratuita o porti la tua licenza (BYOL):

* L'abbonamento garantisce che non vi saranno interruzioni del servizio al termine del periodo di prova gratuito.  Al termine del periodo di prova, ti verrà addebitato un costo orario in base alla quantità di dati sottoposti a backup.
* Se esegui il backup di più dati di quelli consentiti dalla tua licenza BYOL, le operazioni di backup e ripristino dei dati continueranno tramite l'abbonamento a consumo.  Ad esempio, se si dispone di una licenza BYOL da 10 TiB, tutta la capacità oltre i 10 TiB verrà addebitata tramite l'abbonamento PAYGO.


Non ti verrà addebitato alcun costo sul tuo abbonamento a consumo durante il periodo di prova gratuito o se non hai superato la durata della tua licenza BYOL.

Esistono alcuni piani PAYGO per NetApp Backup and Recovery:

* Un pacchetto "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
* Un pacchetto "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Anche questa opzione richiede un abbonamento PAYGO per NetApp Backup and Recovery, ma i sistemi Cloud Volumes ONTAP idonei non prevedono costi.



https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Scopri di più su questi pacchetti di licenze basati sulla capacità"].

Utilizza questi link per abbonarti a NetApp Backup and Recovery dal marketplace del tuo provider cloud:

* AWS: https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^] .
* Azure: https://marketplace.microsoft.com/en-us/product/netapp.cloud-manager?tab=Overview["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^].
* Google Cloud: https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^] .




[[exceeding-license-capacity]]
== Superamento della capacità della licenza

Il superamento della capacità concessa dalla licenza attiva le tariffe PAYGO. Senza un abbonamento PAYGO, non puoi creare nuovi backup, anche se puoi comunque ripristinare i backup esistenti senza garanzia di servizio. Rinnova la licenza prima della scadenza, perché una licenza scaduta impedisce la creazione di nuovi backup e interrompe il servizio.



[[what-happens-when-your-license-expires]]
== Cosa succede quando la tua licenza scade

Quando scade la licenza di NetApp Backup and Recovery:

* I backup dalle policy di backup esistenti e i ripristini continuano a funzionare.
* Non puoi creare nuove policy di backup o estendere la protezione ad altri carichi di lavoro e archivi dati.
* Non puoi utilizzare le nuove funzionalità e i miglioramenti di NetApp Backup and Recovery.
* NetApp technical support per Backup and Recovery non è più disponibile.


Rinnova la tua licenza per:

* Crea e modifica le policy di backup, incluse le policy per i backup coerenti con l'applicazione di database, VM e workload Kubernetes.
* Sfrutta le nuove funzionalità e i miglioramenti di NetApp Backup and Recovery.
* Continua a ricevere il supporto tecnico di NetApp.

