---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery deve prima rilevare i carichi di lavoro per consentirti di proteggerli. 
---
= Scopri i carichi di lavoro KVM in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Individua gli host KVM e le macchine virtuali in NetApp Backup and Recovery così puoi proteggerli con criteri di protezione. Il tuo ambiente KVM deve essere gestito da una piattaforma di gestione come Apache CloudStack prima dell'individuazione.

*Ruolo richiesto nella NetApp Console* super admin di backup e ripristino. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].



[[add-a-management-platform-kvm-host-and-discover-resources]]
== Aggiungi una piattaforma di gestione, un host KVM e scopri le risorse

Aggiungi informazioni sulla piattaforma di gestione e sull'host KVM e lascia che NetApp Backup and Recovery rilevi i carichi di lavoro.


NOTE: Dopo aver aggiunto un sistema storage a NetApp Console, attendi qualche minuto prima di scoprire le risorse. Scoprire le risorse immediatamente dopo aver aggiunto un sistema storage può causare il fallimento della scoperta.

.Passi
. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. In *Carichi di lavoro*, seleziona il riquadro *KVM*.
. Seleziona *Scopri risorse*.
. Inserisci le seguenti informazioni:
+
.. *Tipo di carico di lavoro*: selezionare *KVM*.
.. Se non hai ancora integrato la tua piattaforma di gestione con Backup e Ripristino, seleziona *Aggiungi piattaforma di gestione*.
+
... Inserisci le seguenti informazioni:
+
**** *Indirizzo IP o FQDN della piattaforma di gestione*: Inserisci l'indirizzo IP o un FQDN della piattaforma di gestione.
**** *Chiave API*: inserisci la chiave API da utilizzare per autenticare le richieste API.
**** *Chiave segreta*: inserisci la chiave segreta da utilizzare per autenticare le richieste API.
**** *Porta*: immettere la porta da utilizzare per la comunicazione tra Backup and Recovery e la piattaforma di gestione.
**** *Agenti*: selezionare un agente della console da utilizzare per facilitare la comunicazione tra Backup and Recovery e la piattaforma di gestione.


... Al termine, seleziona *Aggiungi*.


.. *Impostazioni KVM*: Fai quanto segue:
+
... Se non hai ancora memorizzato le credenziali per questo host KVM, seleziona *Aggiungi credenziali*.
+
**** Selezionare l'agente della console da utilizzare con questo host.
**** Inserisci un nome per questa credenziale.
**** Inserisci il nome utente e la password per l'account.
**** Selezionare *Fatto*.


... Aggiungi un nuovo host KVM inserendo le seguenti informazioni:
+
**** *FQDN o indirizzo IP KVM*: immettere l'FQDN o l'indirizzo IP dell'host.
**** *Agenti*: Scegli l'agente della Console da usare per la comunicazione tra NetApp Backup and Recovery e l'host KVM.
**** *Credenziali*: Seleziona una credenziale memorizzata per l'host KVM.




.. *Impostazioni avanzate*: Facoltativamente, inserisci una porta per comunicare con l'host KVM e seleziona la piattaforma di gestione dell'host dall'elenco.


. Seleziona *Scopri*.
+

TIP: Questo processo potrebbe richiedere alcuni minuti.



.Risultato
Il carico di lavoro KVM viene visualizzato nell'elenco dei carichi di lavoro nella pagina Inventario.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Continua alla dashboard NetApp Backup and Recovery

.Passi
. Dal menu NetApp Console , selezionare *Protezione* > *Backup e ripristino*.
. Seleziona il riquadro del carico di lavoro KVM.
. Dal menu Backup e ripristino, seleziona *Dashboard*.
. Esaminare lo stato di salute della protezione dei dati.  Il numero di carichi di lavoro a rischio o protetti aumenta in base ai carichi di lavoro appena scoperti, protetti e sottoposti a backup.

