---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: Puoi ottenere la licenza NetApp Backup and Recovery acquistando un abbonamento annuale o a consumo dal tuo provider cloud oppure acquistando una licenza Bring-Your-Own-License da NetApp.  Per attivare NetApp Backup and Recovery su un sistema, creare backup dei dati di produzione e ripristinare i dati di backup su un sistema di produzione è necessaria una licenza valida. 
---
= Impostare la licenza per NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi ottenere la licenza NetApp Backup and Recovery acquistando un abbonamento annuale o pay-as-you-go (PAYGO) a * NetApp Intelligent Services* dal tuo provider cloud oppure acquistando una licenza bring-your-own (BYOL) da NetApp.  Per attivare NetApp Backup and Recovery su un sistema, creare backup dei dati di produzione e ripristinare i dati di backup su un sistema di produzione è necessaria una licenza valida.

Alcune note prima di proseguire nella lettura:

* Se hai già sottoscritto un abbonamento pay-as-you-go (PAYGO) nel marketplace del tuo provider cloud per un sistema Cloud Volumes ONTAP , sarai automaticamente abbonato anche a NetApp Backup and Recovery .  Non sarà necessario abbonarsi nuovamente.
* La licenza BYOL (Bring Your Own License) NetApp Backup and Recovery è una licenza mobile che puoi utilizzare su tutti i sistemi associati alla tua organizzazione o al tuo account NetApp Console .  Pertanto, se si dispone di una capacità di backup sufficiente da una licenza BYOL esistente, non sarà necessario acquistare un'altra licenza BYOL.
* Se si utilizza una licenza BYOL, si consiglia di sottoscrivere anche un abbonamento PAYGO.  Se esegui il backup di più dati di quelli consentiti dalla tua licenza BYOL o se scade il termine della tua licenza, il backup continua tramite l'abbonamento a consumo, senza alcuna interruzione del servizio.
* Quando si esegue il backup dei dati ONTAP on-premise su StorageGRID, è necessaria una licenza BYOL, ma non vi sono costi per lo spazio di archiviazione del provider cloud.


link:concept-backup-to-cloud.html["Scopri di più sui costi associati all'utilizzo di NetApp Backup and Recovery."]



== Prova gratuita di 30 giorni

È disponibile una prova gratuita di 30 giorni NetApp Backup and Recovery se sottoscrivi un abbonamento pay-as-you-go nel marketplace del tuo provider cloud a * NetApp Intelligent Services*.  La prova gratuita inizia nel momento in cui ti iscrivi all'elenco del marketplace.  Tieni presente che se paghi l'abbonamento al marketplace quando distribuisci un sistema Cloud Volumes ONTAP e poi avvii la prova gratuita NetApp Backup and Recovery 10 giorni dopo, avrai 20 giorni rimanenti per utilizzare la prova gratuita.

Al termine del periodo di prova gratuito, passerai automaticamente all'abbonamento PAYGO senza interruzioni.  Se decidi di non continuare a utilizzare NetApp Backup and Recovery,link:prev-ontap-backup-manage.html["annullare la registrazione NetApp Backup and Recovery dal sistema"] prima della fine del periodo di prova e non ti verrà addebitato alcun costo.



=== Termina la prova gratuita

Se desideri continuare a utilizzare NetApp Backup and Recovery dopo la scadenza del periodo di prova gratuito, devi sottoscrivere un abbonamento a pagamento.  Puoi farlo dall'interfaccia della NetApp Console andando alla sezione fatturazione e selezionando un piano di abbonamento adatto alle tue esigenze.  Se non desideri continuare a utilizzare NetApp Backup and Recovery, puoi interrompere la prova gratuita.

Se termini il periodo di prova gratuito senza sottoscrivere un piano a pagamento, i tuoi dati verranno automaticamente eliminati 60 giorni dopo la fine del periodo di prova gratuito. Facoltativamente, puoi fare in modo che il sistema elimini immediatamente i tuoi dati.

.Passi
. Dalla pagina di destinazione NetApp Backup and Recovery , seleziona *Visualizza prova gratuita*.
. Seleziona *Termina prova gratuita*.
. Seleziona *Elimina i dati subito dopo aver terminato la prova gratuita* per eliminare immediatamente i tuoi dati.
. Digitare *fine prova* nella casella.
. Selezionare *Fine* per confermare.




== Utilizzare un abbonamento NetApp Backup and Recovery PAYGO

Con il pagamento in base al consumo, pagherai al tuo provider cloud i costi di archiviazione degli oggetti e i costi di licenza del backup NetApp su base oraria in un unico abbonamento.  Dovresti abbonarti a * NetApp Intelligent Services* nel Marketplace anche se hai una prova gratuita o se porti la tua licenza (BYOL):

* L'abbonamento garantisce che non vi saranno interruzioni del servizio al termine del periodo di prova gratuito.  Al termine del periodo di prova, ti verrà addebitato un costo orario in base alla quantità di dati sottoposti a backup.
* Se esegui il backup di più dati di quelli consentiti dalla tua licenza BYOL, le operazioni di backup e ripristino dei dati continueranno tramite l'abbonamento a consumo.  Ad esempio, se si dispone di una licenza BYOL da 10 TiB, tutta la capacità oltre i 10 TiB verrà addebitata tramite l'abbonamento PAYGO.


Non ti verrà addebitato alcun costo sul tuo abbonamento a consumo durante il periodo di prova gratuito o se non hai superato la durata della tua licenza BYOL.

Esistono alcuni piani PAYGO per NetApp Backup and Recovery:

* Un pacchetto "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
* Un pacchetto "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Si noti che questa opzione richiede anche un abbonamento PAYGO per backup e ripristino, ma non verranno addebitati costi per i sistemi Cloud Volumes ONTAP idonei.



https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Scopri di più su questi pacchetti di licenze basati sulla capacità"].

Utilizza questi link per abbonarti a NetApp Backup and Recovery dal marketplace del tuo provider cloud:

* AWS: https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^] .
* Azzurro: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^] .
* Google Cloud: https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Per i dettagli sui prezzi, vai all'offerta Marketplace per NetApp Intelligent Services"^] .




== Utilizzare un contratto annuale

Paga annualmente NetApp Backup and Recovery acquistando un contratto annuale.  Sono disponibili con durata di 1, 2 o 3 anni.

Se hai un contratto annuale da un marketplace, tutto il consumo NetApp Backup and Recovery verrà addebitato su quel contratto.  Non è possibile combinare un contratto annuale di mercato con un contratto BYOL.

Quando si utilizza AWS, sono disponibili due contratti annuali da https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["Pagina AWS Marketplace"^] per i sistemi Cloud Volumes ONTAP e ONTAP on-premise:

* Un piano "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
+
Se vuoi utilizzare questa opzione, configura il tuo abbonamento dalla pagina Marketplace e poi https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["associa l'abbonamento alle tue credenziali AWS"^] .  Tieni presente che dovrai pagare anche i tuoi sistemi Cloud Volumes ONTAP utilizzando questo abbonamento contrattuale annuale, poiché puoi assegnare un solo abbonamento attivo alle tue credenziali AWS nella Console.

* Un piano "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Vedi il https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Argomento sulla licenza Cloud Volumes ONTAP"^] per saperne di più su questa opzione di licenza.

+
Se desideri utilizzare questa opzione, puoi impostare il contratto annuale quando crei un sistema Cloud Volumes ONTAP e la Console ti chiederà di iscriverti ad AWS Marketplace.



Quando si utilizza Azure, sono disponibili due contratti annuali da https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Pagina di Azure Marketplace"^] per i sistemi Cloud Volumes ONTAP e ONTAP on-premise:

* Un piano "Cloud Backup" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP locali.
+
Se vuoi utilizzare questa opzione, configura il tuo abbonamento dalla pagina Marketplace e poi https://docs.netapp.com/us-en/console-setup-admin/task-adding-azure-accounts.html#subscribe["associare la sottoscrizione alle credenziali di Azure"^] .  Tieni presente che dovrai pagare anche i tuoi sistemi Cloud Volumes ONTAP utilizzando questo abbonamento contrattuale annuale, poiché puoi assegnare un solo abbonamento attivo alle tue credenziali Azure nella Console.

* Un piano "CVO Professional" che consente di raggruppare Cloud Volumes ONTAP e NetApp Backup and Recovery.  Ciò include backup illimitati per il sistema Cloud Volumes ONTAP utilizzando la licenza (la capacità di backup non viene conteggiata nella capacità concessa in licenza).  Questa opzione non consente di eseguire il backup dei dati ONTAP locali.
+
Vedi il https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Argomento sulla licenza Cloud Volumes ONTAP"^] per saperne di più su questa opzione di licenza.

+
Se si desidera utilizzare questa opzione, è possibile impostare il contratto annuale quando si crea un sistema Cloud Volumes ONTAP e la Console richiede di sottoscrivere l'abbonamento ad Azure Marketplace.



Se utilizzi GCP, contatta il tuo rappresentante commerciale NetApp per acquistare un contratto annuale.  Il contratto è disponibile come offerta privata su Google Cloud Marketplace.

Dopo che NetApp avrà condiviso con te l'offerta privata, potrai selezionare il piano annuale quando ti iscrivi da Google Cloud Marketplace durante l'attivazione NetApp Backup and Recovery .



== Utilizzare una licenza BYOL NetApp Backup and Recovery

Le licenze Bring-your-own di NetApp sono disponibili con durata di 1, 2 o 3 anni.  Si paga solo per i dati che si proteggono, calcolati in base alla capacità logica utilizzata (prima di qualsiasi efficienza) dei volumi ONTAP di origine sottoposti a backup.  Questa capacità è nota anche come Front-End Terabyte (FETB).

La licenza BYOL NetApp Backup and Recovery è una licenza mobile in cui la capacità totale è condivisa tra tutti i sistemi associati all'organizzazione o all'account NetApp Console .  Per i sistemi ONTAP , è possibile ottenere una stima approssimativa della capacità necessaria eseguendo il comando CLI `volume show -fields logical-used-by-afs` per i volumi di cui si intende eseguire il backup.

Se non si dispone di una licenza BYOL NetApp Backup and Recovery , fare clic sull'icona della chat in basso a destra della Console per acquistarne una.

Facoltativamente, se disponi di una licenza basata su nodi non assegnata per Cloud Volumes ONTAP che non utilizzerai, puoi convertirla in una licenza NetApp Backup and Recovery con lo stesso equivalente in dollari e la stessa data di scadenza. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Vai qui per i dettagli"^] .

Per gestire le licenze BYOL è possibile utilizzare la NetApp Console .  È possibile aggiungere nuove licenze, aggiornare quelle esistenti e visualizzare lo stato delle licenze dalla Console.

https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html["Scopri come aggiungere licenze"^].
