---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Per accedere al servizio NetApp Backup and Recovery, utilizzare NetApp Console . 
---
= Accedi a NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per accedere a NetApp Backup and Recovery , utilizzare la NetApp Console .

NetApp Backup and Recovery utilizza la gestione dell'identità e dell'accesso per controllare cosa può fare ogni utente.

Per i dettagli sulle azioni che ogni ruolo può eseguire, vederelink:reference-roles.html["Ruoli utente di NetApp Backup and Recovery"] .

Per accedere alla NetApp Console, puoi utilizzare le credenziali del sito di supporto NetApp oppure registrarti per accedere alla NetApp Console utilizzando il tuo indirizzo email e una password. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["Scopri di più sull'accesso"^] .

*Ruolo NetApp Console obbligatorio* Ruolo di super amministratore di Backup and Recovery o di amministratore di ripristino di Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .

Per aggiungere un agente Console, è necessario disporre del ruolo di super amministratore di Backup e ripristino.

.Passi
. Apri un browser web e vai su https://console.netapp.com/["NetApp Console"^] .
+
Viene visualizzata la pagina di accesso NetApp Console .

. Accedi alla Console.
. Dal menu di navigazione a sinistra della Console, seleziona *Protezione* > *Backup e ripristino*.
+
** Se è la prima volta che accedi a Backup and Recovery e non hai ancora aggiunto un sistema alla pagina *Sistemi*, Backup and Recovery visualizza la pagina di destinazione "Benvenuti nel nuovo NetApp Backup and Recovery" con un'opzione per aggiungere un sistema. Per i dettagli sull'aggiunta di un sistema alla pagina *Sistemi*, fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introduzione alla modalità standard NetApp Console"^].
** Se si accede a Backup and Recovery per la prima volta e si ha un sistema nella Console ma non sono state rilevate risorse, viene visualizzata la pagina _Benvenuti nel nuovo NetApp Backup and Recovery_ con l'opzione *Rileva risorse*.


. Se non lo hai ancora fatto, seleziona l'opzione *Scopri e gestisci*.
+
** Per i carichi di lavoro di Microsoft SQL Server, fare riferimento alink:br-start-discover.html["Scopri i carichi di lavoro di Microsoft SQL Server"] .
** Per i carichi di lavoro VMware, fare riferimento alink:br-use-vmware-discovery.html["Scopri i carichi di lavoro VMware"] .
** Per i carichi di lavoro KVM, fare riferimento alink:br-start-discover-kvm.html["Scopri i carichi di lavoro KVM"] .
** Per i carichi di lavoro di Oracle Database, fare riferimento a link:br-start-discover-oracle.html["Scopri i carichi di lavoro Oracle Database"].
** Per i carichi di lavoro Hyper-V, fare riferimento alink:br-start-discover-hyperv.html["Scopri i carichi di lavoro Hyper-V"] .
** Per i carichi di lavoro Kubernetes, fare riferimento alink:br-start-discover-kubernetes.html["Scopri i carichi di lavoro di Kubernetes"] .



