---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: 'È possibile ripristinare file o cartelle da un disco di macchina virtuale (VMDK) su un sistema operativo guest Windows.' 
---
= Requisiti e limitazioni durante il ripristino di file e cartelle guest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare file o cartelle da un disco di macchina virtuale (VMDK) su un sistema operativo guest Windows o Linux.



== Flusso di lavoro di ripristino degli ospiti

Le operazioni di ripristino del sistema operativo guest includono i seguenti passaggi:

. Allegare
+
Collega un disco virtuale a una macchina virtuale guest o a una macchina virtuale proxy e avvia una sessione di ripristino dei file guest.

. Aspettare
+
Attendi il completamento dell'operazione di collegamento prima di poter esplorare e ripristinare. Al termine dell'operazione di collegamento, viene creata automaticamente una sessione di ripristino del file guest.

. Seleziona file o cartelle
+
Esplora o cerca i file del disco virtuale e seleziona uno o più file o cartelle da ripristinare.

. Ripristinare
+
Ripristina i file o le cartelle selezionati in una posizione specificata.





== Prerequisiti per il ripristino di file e cartelle guest

Verifica tutti i requisiti prima di ripristinare file o cartelle da un VMDK.

* Gli strumenti VMware devono essere installati e in esecuzione.
+
NetApp Backup and Recovery utilizza le informazioni provenienti dagli strumenti VMware per stabilire una connessione al sistema operativo guest VMware.

* È necessario conoscere lo snapshot di backup e il VMDK da cui eseguire il ripristino.
* Il disco virtuale da collegare deve trovarsi in un backup NetApp Backup and Recovery .
+
Il disco virtuale che contiene il file o la cartella che si desidera ripristinare deve trovarsi in un backup della VM eseguito tramite NetApp Backup and Recovery.

* Per utilizzare una proxy VM, la proxy VM deve essere configurata.
+
Se si desidera collegare un disco virtuale a una VM proxy, la VM proxy deve essere configurata prima dell'avvio dell'operazione di collegamento e ripristino.

* Per i file con nomi in un alfabeto diverso dall'inglese, è necessario ripristinarli in una directory e non come un singolo file.
+
È possibile ripristinare i file con nomi non alfabetici, come i Kanji giapponesi, ripristinando la directory in cui si trovano i file.



Per le informazioni più recenti sul supporto dei sistemi operativi guest, fare riferimento a https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp (IMT)"^].



=== Guest Windows

* Il sistema operativo guest Windows deve eseguire Windows Server 2008 R2 o versione successiva.
+
Per le informazioni più recenti sulle versioni supportate, fare riferimento a https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp (IMT)"^] .

* Le credenziali per la macchina virtuale di destinazione utilizzano il dominio predefinito o l'account amministratore locale con nome utente "Amministratore". Prima di avviare l'operazione di ripristino, configurare le credenziali per la macchina virtuale a cui si desidera collegare il disco virtuale. Le credenziali sono necessarie sia per le operazioni di collegamento che di ripristino. Gli utenti del gruppo di lavoro possono utilizzare l'account amministratore locale integrato.
+

IMPORTANT: Se è necessario utilizzare un account che non è l'account amministratore predefinito, ma dispone di privilegi amministrativi all'interno della VM, è necessario disabilitare UAC sulla VM guest.





=== guest Linux

* Sono supportate le seguenti distribuzioni di sistemi operativi guest:
+
** Red Hat Enterprise Linux
** Ubuntu
** Debian


* L'account Run-As necessita dei permessi di root o sudo.
* Per il ripristino tra macchine virtuali (ripristino su una macchina virtuale Linux diversa), SSH deve essere in esecuzione sulla macchina virtuale di destinazione.




== Limitazioni del ripristino dei file guest

Prima di ripristinare un file o una cartella da un sistema operativo guest, è necessario essere a conoscenza delle limitazioni della funzionalità.

* Non è possibile ripristinare tipi di dischi dinamici all'interno di un sistema operativo guest.
* Se si ripristina un file o una cartella crittografati, l'attributo di crittografia non viene mantenuto.
* Non è possibile ripristinare file o cartelle in una cartella crittografata.
* I file e le cartelle nascosti vengono visualizzati nella pagina di esplorazione dei file e non è possibile filtrarli.
* Non è possibile ripristinare file o cartelle tra macchine virtuali con sistemi operativi diversi (quando si esegue il ripristino su una macchina virtuale diversa, il tipo di sistema operativo di destinazione deve essere uguale al tipo di sistema operativo di origine).
* Non è possibile ripristinare da un file system NTFS a un file system FAT.
+
Quando si tenta di ripristinare dal formato NTFS al formato FAT, il descrittore di sicurezza NTFS non viene copiato perché il file system FAT non supporta gli attributi di sicurezza di Windows.

* Non è possibile ripristinare i file guest da un VMDK clonato o da un VMDK non inizializzato.
* Non è possibile ripristinare la struttura della directory di un file.
+
Quando si ripristina un file da una directory nidificata, il sistema ripristina solo il file, non la struttura della directory. Per ripristinare l'intero albero delle directory, copiare la directory di livello superiore.

* Non è possibile ripristinare i file guest da una VM vVol a un host alternativo.
* Non è possibile ripristinare i file guest crittografati.

