---
sidebar: sidebar 
permalink: br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html 
keywords:  
summary: 'Quando si tenta di ripristinare un file guest, potrebbero verificarsi situazioni in cui la sessione di ripristino del file guest è vuota, l"operazione di collegamento del disco di ripristino del file guest non riesce o i backup non vengono scollegati dopo l"interruzione della sessione di ripristino del file guest.' 
---
= Risolvi i problemi relativi al ripristino dei file guest di VMware in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se riscontri problemi durante il ripristino di un file guest, utilizza questi scenari per identificare e correggere il problema.



[[guest-file-restore-session-is-blank]]
== La sessione di ripristino dei file guest è vuota

Questo problema si verifica se si crea una sessione di ripristino file guest e il sistema operativo guest si riavvia durante la sessione. I VMDK nel sistema operativo guest potrebbero rimanere offline, pertanto l'elenco delle sessioni di ripristino dei file guest è vuoto.

Per correggere il problema, rimettere manualmente online i VMDK nel sistema operativo guest. Quando i VMDK sono online, la sessione di ripristino dei file guest visualizzerà il contenuto corretto.



[[guest-file-restore-attach-disk-operation-fails]]
== L'operazione di collegamento del disco al ripristino del file guest non riesce

Questo problema si verifica quando avvii un'operazione di ripristino dei file guest, ma l'operazione di collegamento del disco non riesce anche se VMware Tools è in esecuzione e le credenziali del sistema operativo guest sono corrette. Se questo accade, viene restituito il seguente errore:

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMware Tools is running properly on the system and that the account used is an Administrator account. Error is SystemError vix error codes = (3016, 0).`

Per risolvere il problema, riavvia il servizio VMware Tools di Windows sul sistema operativo guest e poi riprova l'operazione di ripristino dei file del sistema operativo guest.



[[backups-are-not-detached-after-guest-file-restore-session-is-discontinued]]
== I backup non vengono scollegati dopo l'interruzione della sessione di ripristino dei file guest

Questo problema si verifica quando si esegue un'operazione di ripristino di file guest da un backup coerente con la VM. Mentre la sessione di ripristino dei file guest è attiva, viene eseguito un altro backup coerente con la VM per la stessa VM. Quando la sessione di ripristino dei file guest viene disconnessa, manualmente o automaticamente dopo 24 ore, i backup per la sessione non vengono scollegati.

Per correggere il problema, scollegare manualmente i VMDK collegati alla sessione di ripristino dei file guest attiva.
