---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Proteggi i tuoi carichi di lavoro Hyper-V con NetApp Backup and Recovery. 
---
= Ripristina i carichi di lavoro Hyper-V con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ripristina i carichi di lavoro Hyper-V da snapshot, da un backup del carico di lavoro replicato su un archivio secondario o da backup archiviati nell'archivio oggetti utilizzando NetApp Backup and Recovery.

.Ripristina da queste posizioni
È possibile ripristinare i carichi di lavoro da diverse posizioni di partenza:

* Ripristina da una posizione primaria (snapshot locale)
* Ripristina da una risorsa replicata su un archivio secondario
* Ripristina da un backup di archiviazione di oggetti


.Ripristinare questi punti
È possibile ripristinare i dati in questi punti:

* Ripristina la posizione originale
* Ripristina in una posizione alternativa


.Considerazioni sul ripristino da storage di oggetti
Se selezioni un file di backup nell'archiviazione oggetti e per quel backup è attiva la protezione ransomware (se hai abilitato DataLock e Ransomware Resilience nei criteri di backup), ti verrà richiesto di eseguire un ulteriore controllo di integrità sul file di backup prima di ripristinare i dati.  Ti consigliamo di eseguire la scansione.


TIP: Per accedere al contenuto del file di backup, dovrai sostenere costi di uscita aggiuntivi da parte del tuo provider cloud.



== Come funziona il ripristino dei carichi di lavoro

Quando si ripristinano i carichi di lavoro, si verifica quanto segue:

* Quando si ripristina un carico di lavoro da un file di backup locale, NetApp Backup and Recovery crea una _nuova_ risorsa utilizzando i dati del backup.
* Quando si esegue il ripristino da un carico di lavoro replicato, è possibile ripristinare il carico di lavoro sul sistema originale o su un sistema ONTAP locale.


Dalla pagina Ripristina (nota anche come Cerca e ripristina), puoi ripristinare una risorsa anche se non ricordi il nome esatto, la posizione in cui si trova o la data dell'ultima volta in cui era in buone condizioni. È possibile cercare l'istantanea utilizzando i filtri.



== Ripristina i dati del carico di lavoro dall'opzione Ripristina (Cerca e ripristina)

Ripristinare i carichi di lavoro Hyper-V utilizzando l'opzione Ripristina. È possibile cercare l'istantanea in base al nome o utilizzando i filtri.

*Ruolo di console obbligatorio* Ruolo di super amministratore di Backup e ripristino o di amministratore di ripristino di Backup e ripristino. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .

.Passi
. Dal menu NetApp Backup and Recovery , selezionare *Ripristina*.
. Dall'elenco a discesa a destra del campo di ricerca del nome, selezionare *Hyper-V*.
. Immettere il nome della risorsa che si desidera ripristinare oppure filtrare in base al nome della VM, all'host della VM o al pool di archiviazione in cui si trova la risorsa che si desidera ripristinare.
+
Viene visualizzato un elenco di snapshot che corrispondono ai criteri di ricerca.

. Selezionare il pulsante *Ripristina* per lo snapshot che si desidera ripristinare.
+
Viene visualizzato un elenco di possibili punti di ripristino.

. Seleziona il punto di ripristino che desideri utilizzare.
. Selezionare una posizione di origine dello snapshot.
. Selezionare *Avanti* per continuare.
. Scegli la destinazione e le impostazioni di ripristino:


[discrete]
===== Selezione della destinazione

[role="tabbed-block"]
====
.Ripristina nella posizione originale
--
Quando si ripristina la posizione originale, è possibile visualizzare le impostazioni di destinazione espandendo la sezione *Impostazioni di destinazione*, ma non è possibile modificarle.

. Nella sezione *Opzioni post-ripristino*, prendere in considerazione la seguente opzione:
+
** *Avvia la macchina virtuale*: abilita questa opzione per avviare la nuova macchina virtuale dopo il ripristino.


. Selezionare *Ripristina*.


--
.Ripristina in posizione alternativa
--
. Nella sezione *Impostazioni destinazione*: inserisci le seguenti informazioni:
+
** *FQDN o indirizzo IP Hyper-V*: immettere il nome di dominio completo o l'indirizzo IP dell'host Hyper-V di destinazione.
** *Rete*: seleziona la rete di destinazione in cui desideri ripristinare lo snapshot.
** *Nome macchina virtuale*: immettere il nome della VM che si desidera ripristinare.
** *Posizione di destinazione*: immettere la cartella di destinazione o la condivisione CIFS che deve contenere i dati ripristinati.


. Nella sezione *Opzioni pre-ripristino*, prendi in considerazione le seguenti opzioni:
+
** *Ripristino rapido*: abilita questa opzione per rendere immediatamente disponibile la VM ripristinata. Dall'archivio oggetti vengono ripristinati solo i file necessari per eseguire la macchina virtuale, anziché l'intero volume.


. Nella sezione *Opzioni di ripristino post*, prendi in considerazione le seguenti opzioni:
+
** *Avvia la macchina virtuale*: abilita questa opzione per avviare la nuova macchina virtuale dopo il ripristino.


. Selezionare *Ripristina*.


--
====