---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery consente di ripristinare le applicazioni protette tramite una policy di protezione. 
---
= Ripristina le applicazioni Kubernetes utilizzando l'interfaccia utente web
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery consente di ripristinare le applicazioni protette tramite una policy di protezione. Per ripristinare un'applicazione, è necessario che quest'ultima disponga di almeno un punto di ripristino. Un punto di ripristino può essere costituito dallo snapshot locale o dal backup nell'archivio oggetti (o da entrambi). È possibile ripristinare un'applicazione utilizzando l'archivio locale, secondario o dell'archivio oggetti.

.Prima di iniziare
Se si sta ripristinando un'applicazione di cui è stato eseguito il backup utilizzando Trident Protect, assicurarsi che Trident Protect sia installato sia sul cluster di origine che sul cluster di destinazione.

.Ruolo richiesto NetApp Console
Amministratore dell'organizzazione o amministratore SnapCenter . link:reference-roles.html["Scopri di più sui ruoli di accesso a NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .

.Passi
. Nel menu NetApp Backup e ripristino, seleziona *Ripristina*.
. Scegli un'applicazione Kubernetes dall'elenco e seleziona *Visualizza e ripristina* per quell'applicazione.
+
Viene visualizzato l'elenco dei punti di ripristino.

. Seleziona il pulsante *Ripristina* per il punto di ripristino che si desidera utilizzare.


[discrete]
===== Impostazioni generali

. Scegli la posizione di origine da cui eseguire il ripristino.
. Selezionare il cluster di destinazione dall'elenco *Cluster*.
+

NOTE: Al momento non è supportato il ripristino di uno snapshot locale creato da Trident Protect su un cluster diverso.

. Scegli se ripristinare negli spazi dei nomi originali o in nuovi spazi dei nomi.
. Se si sceglie di ripristinare su nuovi namespace, immettere il namespace di destinazione o i namespace di destinazione da utilizzare.
. Selezionare *Avanti*.


[discrete]
===== Selezione delle risorse

. Scegli se desideri ripristinare tutte le risorse associate all'applicazione oppure utilizzare un filtro per selezionare risorse specifiche da ripristinare:


[role="tabbed-block"]
====
.Ripristina tutte le risorse
--
. Seleziona *Ripristina tutte le risorse*.
. Selezionare *Avanti*.


--
.Ripristina risorse specifiche
--
. Seleziona *Risorse selettive*.
. Scegli il comportamento del filtro delle risorse.  Se scegli *Includi*, le risorse selezionate verranno ripristinate.  Se si sceglie *Escludi*, le risorse selezionate non verranno ripristinate.
. Selezionare *Aggiungi regole* per aggiungere regole che definiscono i filtri per la selezione delle risorse.  Per filtrare le risorse è necessaria almeno una regola.
+
Ogni regola può filtrare in base a criteri quali lo spazio dei nomi della risorsa, le etichette, il gruppo, la versione e il tipo.

. Selezionare *Salva* per salvare ciascuna regola.
. Dopo aver aggiunto tutte le regole necessarie, seleziona *Cerca* per visualizzare le risorse disponibili nell'archivio di backup che corrispondono ai criteri di filtro.
+

NOTE: Le risorse mostrate sono le risorse attualmente presenti nel cluster.

. Una volta soddisfatti dei risultati, selezionare *Avanti*.


--
====
[discrete]
===== Impostazioni di destinazione

. Espandi la sezione *Impostazioni di destinazione* e scegli se ripristinare sulla classe di archiviazione predefinita, su una classe di archiviazione diversa oppure, se stai eseguendo il ripristino su un cluster diverso, di mappare le classi di archiviazione sul cluster di destinazione.
. Se si sceglie di ripristinare in una classe di archiviazione diversa, selezionare una classe di archiviazione di destinazione che corrisponda a ciascuna classe di archiviazione di origine.
. Facoltativamente, se si sta ripristinando un backup o uno snapshot creato con Trident Protect, visualizzare i dettagli del AppVault utilizzato come bucket di archiviazione per l'operazione di ripristino. Se vi è una modifica nell'ambiente o nello stato di AppVault, selezionare *Sync App Vault* per aggiornare i dettagli.
+

NOTE: Se è necessario creare un AppVault su un cluster Kubernetes per facilitare il ripristino di un backup o di uno snapshot creato utilizzando Trident Protect, fare riferimento a  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-appvault-custom-resources.html["Utilizzare gli oggetti Trident Protect AppVault per gestire i bucket"].

. Facoltativamente, espandi la sezione *Script di ripristino* e abilita l'opzione *Postscript* per scegliere un modello di hook di esecuzione che verrà eseguito al termine dell'operazione di ripristino. Se necessario, inserisci gli argomenti di cui lo script ha bisogno e aggiungi selettori di etichetta per filtrare le risorse in base alle etichette delle risorse.
. Selezionare *Ripristina*.

