---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: Monitorando lo stato dei carichi di lavoro sarai a conoscenza di eventuali problemi relativi alla protezione dei carichi di lavoro e potrai adottare misure per risolverli.  Visualizza lo stato dei tuoi backup e ripristini e rispondi a tutti gli avvisi che compaiono nella dashboard NetApp Backup and Recovery .  È possibile esaminare il riepilogo della protezione, il riepilogo del ripristino, il riepilogo del sistema e altro ancora. 
---
= Visualizza lo stato di protezione nella dashboard di backup e ripristino
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Monitora lo stato di salute dei tuoi carichi di lavoro per identificare i problemi di protezione e rispondere agli avvisi. Visualizza lo stato dei backup e dei ripristini e consulta i riepiloghi di Sistema, Protezione, Job e Ripristino nella NetApp Backup and Recovery Dashboard.

*Ruolo della NetApp Console richiesto* Backup and Recovery super admin, Backup and Recovery backup admin, Backup and Recovery restore admin, Backup and Recovery clone admin o Backup and Recovery backup viewer role. Se stai proteggendo dati archiviati su un cluster Cloud Volumes ONTAP, è richiesto anche il ruolo Cloud Volumes ONTAP Admin. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].

.Passi
. Dal menu NetApp Console, seleziona *Protezione* > *Backup and Recovery*.
. Selezionare un riquadro del carico di lavoro (ad esempio, Microsoft SQL Server).
. Dal menu Backup e ripristino, seleziona *Dashboard*.
+
È possibile esaminare i seguenti tipi di informazioni:

+
** Numero di host o VM scoperti
** Numero di cluster Kubernetes scoperti
** Numero di destinazioni di backup su storage di oggetti
** Numero di vCenter
** Numero di cluster di archiviazione in ONTAP






[[view-the-protection-summary]]
== Visualizza il riepilogo della protezione

Esaminare le seguenti informazioni nel Riepilogo della protezione:

* Numero totale di database, VM e datastore protetti e non protetti.
+

TIP: Un database protetto è un database a cui è assegnata una policy di backup.  Un database non protetto è un database a cui non è assegnata alcuna policy di backup.

* Numero di backup riusciti, con avviso o non riusciti.
* La capacità totale rilevata dal servizio di backup e la capacità protetta rispetto a quella non protetta.  Passa il mouse sull'icona "*i*" per visualizzare i dettagli.




[[view-the-job-summary]]
== Visualizza il riepilogo del lavoro

Consulta il numero totale di attività completate, in corso o non riuscite nel riepilogo attività.

.Passi
. Per ogni distribuzione dei processi, modifica il filtro per visualizzare il riepilogo dei processi non riusciti, in esecuzione e completati in base al numero di giorni, ad esempio gli ultimi 30 giorni, gli ultimi 7 giorni, le ultime 24 ore o l'ultimo anno.
. Visualizza i dettagli dei processi non riusciti, in esecuzione e completati selezionando *Visualizza monitoraggio processi*.




[[view-the-restore-summary]]
== Visualizza il riepilogo del ripristino

Esamina le seguenti informazioni nel riepilogo del ripristino:

* Numero totale di processi di ripristino eseguiti
* La quantità totale di capacità che è stata ripristinata
* Numero di processi di ripristino eseguiti su storage locale, secondario e di oggetti.  Passa il mouse sul grafico per visualizzare i dettagli.

