---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Proteggi i tuoi carichi di lavoro Hyper-V con NetApp Backup and Recovery. 
---
= Ripristina i carichi di lavoro Hyper-V con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ripristina i carichi di lavoro Hyper-V da snapshot locali, backup replicati su storage secondario o backup in storage a oggetti utilizzando NetApp Backup and Recovery.

.Ripristina da queste posizioni
Puoi ripristinare i carichi di lavoro da queste posizioni:

* Ripristina da una posizione primaria (snapshot locale)
* Ripristina da una risorsa replicata su un archivio secondario
* Ripristina da un backup di archiviazione di oggetti


.Ripristinare questi punti
Puoi ripristinare i dati verso queste destinazioni:

* Ripristina nella posizione originale (da storage primario, secondario e storage a oggetti)
* Ripristina in una posizione alternativa (da storage primario, secondario e a oggetti)


.Considerazioni sul ripristino da storage di oggetti
Se selezioni un file di backup nello storage a oggetti e la protezione anti-ransomware è attiva per quel backup perché hai abilitato DataLock e la protezione anti-ransomware nella policy di backup, ti viene richiesto di eseguire un controllo di integrità aggiuntivo prima di ripristinare i dati. Ti consigliamo di eseguire la scansione.


TIP: Per accedere al contenuto del file di backup, dovrai sostenere costi di uscita aggiuntivi da parte del tuo provider cloud.



[[how-restoring-workloads-works]]
== Come funziona il ripristino dei carichi di lavoro

Quando ripristini un carico di lavoro, si verificano le seguenti situazioni:

* Quando si ripristina un carico di lavoro da un file di backup locale, NetApp Backup and Recovery crea una _nuova_ risorsa utilizzando i dati del backup.
* Quando si esegue il ripristino da un carico di lavoro replicato, è possibile ripristinare il carico di lavoro sul sistema originale o su un sistema ONTAP locale.


Dalla pagina Ripristina, puoi ripristinare una risorsa anche se non ricordi il nome esatto, la posizione o la data dell'ultimo backup valido. Puoi cercare l'istantanea utilizzando i filtri.



[[restore-hyper-v-workloads]]
== Ripristinare i carichi di lavoro Hyper-V

Ripristina i carichi di lavoro Hyper-V utilizzando il menu Ripristina. Puoi cercare uno snapshot per nome o utilizzando i filtri.

*Ruolo di console obbligatorio* Ruolo di super amministratore di Backup e ripristino o di amministratore di ripristino di Backup e ripristino. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .

.Passi
. Dal menu NetApp Backup and Recovery , selezionare *Ripristina*.
. Dall'elenco a discesa a destra del campo di ricerca del nome, selezionare *Hyper-V*.
. Inserisci il nome della risorsa che vuoi ripristinare oppure filtra per nome della VM, host della VM o pool di storage in cui si trova la risorsa.
+
Viene visualizzato un elenco di snapshot che corrispondono ai criteri di ricerca.

. Selezionare il pulsante *Ripristina* per lo snapshot che si desidera ripristinare.
+
Viene visualizzato un elenco di possibili punti di ripristino.

. Seleziona il punto di ripristino che desideri utilizzare.
. Selezionare una posizione di origine dello snapshot.
. Selezionare *Avanti* per continuare.
. Scegli la destinazione e le impostazioni di ripristino:
+
[discrete]
===== Selezione della destinazione

+
[role="tabbed-block"]
====
.Ripristina nella posizione originale
--
.. Seleziona il riquadro *Posizione originale*. Quando ripristini nella posizione originale, puoi visualizzare le impostazioni di destinazione espandendo la sezione *Impostazioni di destinazione*, ma non puoi modificarle.
.. Nella sezione *Opzioni post-ripristino*, prendere in considerazione la seguente opzione:
+
*** *Avvia la macchina virtuale*: abilita questa opzione per avviare la nuova macchina virtuale dopo il ripristino.




--
.Ripristina in posizione alternativa
--
.. Selezionare il riquadro *Posizione alternativa*.
.. Nella sezione *Impostazioni destinazione*, inserisci le seguenti informazioni:
+
*** *FQDN o indirizzo IP Hyper-V*: immettere il nome di dominio completo o l'indirizzo IP dell'host Hyper-V di destinazione.
*** *Rete*: seleziona la rete di destinazione in cui desideri ripristinare lo snapshot.
*** *Nome macchina virtuale*: immettere il nome della VM che si desidera ripristinare.
*** *Posizione di destinazione*: immettere la cartella di destinazione o la condivisione CIFS che deve contenere i dati ripristinati.


.. Nella sezione *Archiviazione di destinazione* (visibile solo durante il ripristino da storage a oggetti):
+
*** *Modifica posizione di archiviazione predefinita*: Abilita questa opzione per ripristinare un backup dell'archivio di oggetti in una posizione diversa se la posizione di archiviazione di origine non è raggiungibile o è piena. Scegli un cluster, una storage VM o un aggregate diverso da utilizzare.


.. Nella sezione *Opzioni pre-ripristino*, prendi in considerazione le seguenti opzioni:
+
*** *Ripristino rapido*: abilita questa opzione per rendere immediatamente disponibile la VM ripristinata. Dall'archivio oggetti vengono ripristinati solo i file necessari per eseguire la macchina virtuale, anziché l'intero volume.


.. Nella sezione *Opzioni post-ripristino*, prendi in considerazione le seguenti opzioni:
+
*** *Avvia la macchina virtuale*: abilita questa opzione per avviare la nuova macchina virtuale dopo il ripristino.




--
====
. Selezionare *Ripristina*.

