---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: È possibile eseguire il backup dei dati delle applicazioni Microsoft SQL Server dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure e StorageGRID, garantendo la protezione dei dati. I backup vengono generati automaticamente e archiviati in un archivio oggetti nel tuo account cloud pubblico o privato.  È possibile implementare una strategia 3-2-1, in cui si hanno 3 copie dei dati di origine su 2 sistemi di archiviazione diversi, oltre a 1 copia nel cloud. 
---
= Panoramica sulla protezione dei carichi di lavoro Microsoft SQL con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteggi i dati delle tue applicazioni Microsoft SQL Server dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure o StorageGRID utilizzando NetApp Backup and Recovery. I backup vengono generati automaticamente e archiviati in un archivio oggetti nel tuo account cloud pubblico o privato, in base ai criteri che crei.  È possibile implementare una strategia 3-2-1, in cui si hanno 3 copie dei dati di origine su 2 sistemi di archiviazione diversi, oltre a 1 copia nel cloud.

I vantaggi dell'approccio 3-2-1 includono:

* Le copie multiple dei dati garantiscono una protezione multilivello contro le minacce informatiche interne (interne) ed esterne.
* Diversi tipi di supporto garantiscono la fattibilità del failover in caso di guasto fisico o logico di un tipo di supporto.
* La copia in loco facilita ripristini rapidi, mentre le copie fuori sede sono disponibili nel caso in cui la copia in loco venga compromessa.


NetApp Backup and Recovery sfrutta la tecnologia di replicazione dei dati NetApp SnapMirror per garantire che tutti i backup siano completamente sincronizzati creando copie snapshot e trasferendole nelle posizioni di backup.

È possibile raggiungere i seguenti obiettivi di protezione:

* link:concept-start-prereq-snapcenter-import.html["Configurare elementi aggiuntivi se si importa da SnapCenter"]
* link:br-start-discover.html["Scopri i carichi di lavoro di Microsoft SQL Server e, facoltativamente, importa le risorse SnapCenter"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro con snapshot locali sullo storage primario ONTAP locale"]
* link:br-use-mssql-backup.html["Replicare i carichi di lavoro sullo storage secondario ONTAP"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro in una posizione di archiviazione oggetti"]
* link:br-use-mssql-backup.html["Esegui subito il backup dei carichi di lavoro"]
* link:br-use-mssql-restore-overview.html["Ripristinare i carichi di lavoro"]
* link:br-use-mssql-clone.html["Clonazione dei carichi di lavoro"]
* link:br-use-manage-inventory.html["Gestire l'inventario dei carichi di lavoro"]
* link:br-use-manage-snapshots.html["Gestisci gli snapshot"]


Per eseguire il backup dei carichi di lavoro, in genere si creano policy che regolano le operazioni di backup e ripristino. Vedere link:br-use-policies-create.html["Creare politiche"] per maggiori informazioni.

.Destinazioni di backup supportate
NetApp Backup and Recovery consente di eseguire il backup di istanze e database di Microsoft SQL Server dai seguenti sistemi di origine ai seguenti sistemi secondari e storage di oggetti nei provider di cloud pubblici e privati.  Le copie snapshot risiedono sul sistema di origine.

[cols="33,33,33"]
|===
| Sistema sorgente | Sistema secondario (Replicazione) | Archivio oggetti di destinazione (backup) 


| Cloud Volumes ONTAP in AWS | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP in Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Azure Blob ONTAP S3 


| Sistema ONTAP in sede | Cloud Volumes ONTAP Sistema ONTAP locale | Blob di Azure Amazon S3 NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA ifdef::gcp[] endif::gcp[] ifdef::gcp[] endif::gcp[] 
|===
.Destinazioni di ripristino supportate
È possibile ripristinare istanze e database di Microsoft SQL Server da un backup che risiede nell'archivio primario o in un sistema secondario (un volume replicato) o nell'archivio oggetti (un file di backup) nei seguenti sistemi.  Le copie snapshot risiedono sul sistema di origine e possono essere ripristinate solo su quello stesso sistema.

[cols="33,33,33"]
|===
2+| Dalla posizione del file di backup | Al sistema di destinazione 


| *Archivio oggetti (backup)* | *Sistema secondario (replicazione)* |  


| Amazon S3 | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Cloud Volumes nel sistema ONTAP locale AWS ONTAP S3 


| Blob azzurro | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure ONTAP S3 ifdef::gcp[] endif::gcp[] 


| StorageGRID | Cloud Volumes ONTAP Sistema ONTAP locale | Sistema ONTAP on-premise ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===

NOTE: I riferimenti ai "sistemi ONTAP locali" includono i sistemi FAS e AFF .
