---
sidebar: sidebar 
permalink: br-use-mssql-restore-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'I backup dei dati sono disponibili per il ripristino dalle posizioni in cui sono stati creati i backup, tra cui snapshot, repliche e backup nell"archiviazione di oggetti.  Esaminare le posizioni di partenza del ripristino, i punti di ripristino e i tipi di risorse da ripristinare.' 
---
= Panoramica del ripristino dei carichi di lavoro Microsoft SQL tramite NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I backup dei dati di Microsoft SQL Server da NetApp Backup and Recovery sono disponibili per il ripristino dalle posizioni in cui sono stati spostati i backup: snapshot, repliche o backup nell'archiviazione di oggetti.  È possibile ripristinare un carico di lavoro sul sistema originale, su un sistema diverso che utilizza lo stesso account cloud o su un sistema ONTAP locale.  Esaminare le posizioni di partenza del ripristino, i punti di ripristino e i tipi di risorse da ripristinare.

.Ripristina da queste posizioni
È possibile ripristinare i carichi di lavoro da diverse posizioni di partenza:

* Ripristina da una posizione primaria
* Ripristina da una risorsa replicata
* Ripristina da un backup dell'archivio oggetti


.Ripristinare questi punti
È possibile ripristinare i dati all'ultimo snapshot o a questi punti:

* Ripristina da snapshot
* Ripristina un punto specifico nel tempo.  Ciò è utile se si conosce il nome e la posizione del file, nonché la data dell'ultima volta in cui è stato in buone condizioni.
* Ripristina l'ultimo backup




== Cosa c'è dopo?

Per i dettagli su come ripristinare i carichi di lavoro, vederelink:br-use-mssql-restore.html["Ripristinare i carichi di lavoro"] .
