---
sidebar: sidebar 
permalink: br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html 
keywords:  
summary: 'Quando si tenta di ripristinare un file guest, potrebbero verificarsi situazioni in cui la sessione di ripristino del file guest è vuota, l"operazione di collegamento del disco di ripristino del file guest non riesce o i backup non vengono scollegati dopo l"interruzione della sessione di ripristino del file guest.' 
---
= Risoluzione dei problemi di ripristino dei file guest
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si tenta di ripristinare un file guest, è possibile che si verifichi uno dei seguenti scenari.



== La sessione di ripristino dei file guest è vuota

Questo problema si verifica se si crea una sessione di ripristino file guest e il sistema operativo guest si riavvia durante la sessione. I VMDK nel sistema operativo guest potrebbero rimanere offline, pertanto l'elenco delle sessioni di ripristino dei file guest è vuoto.

Per correggere il problema, rimettere manualmente online i VMDK nel sistema operativo guest. Quando i VMDK sono online, la sessione di ripristino dei file guest visualizzerà il contenuto corretto.



== L'operazione di collegamento del disco al ripristino del file guest non riesce

Questo problema si verifica quando si avvia un'operazione di ripristino di file guest, ma l'operazione di collegamento del disco non riesce anche se VMware Tools è in esecuzione e le credenziali del sistema operativo guest sono corrette. Se ciò si verifica, viene restituito il seguente errore:

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMWare tools is running properly on system and account used is Administrator account, Error is SystemError vix error codes = (3016, 0).`

Per correggere il problema, riavviare il servizio VMware Tools Windows sul sistema operativo guest, quindi riprovare l'operazione di ripristino del file guest.



== I backup non vengono scollegati dopo l'interruzione della sessione di ripristino dei file guest

Questo problema si verifica quando si esegue un'operazione di ripristino di file guest da un backup coerente con la VM. Mentre la sessione di ripristino dei file guest è attiva, viene eseguito un altro backup coerente con la VM per la stessa VM. Quando la sessione di ripristino dei file guest viene disconnessa, manualmente o automaticamente dopo 24 ore, i backup per la sessione non vengono scollegati.

Per correggere il problema, scollegare manualmente i VMDK collegati alla sessione di ripristino dei file guest attiva.
