---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i tuoi carichi di lavoro VMware con NetApp Backup and Recovery. 
---
= Proteggi i carichi di lavoro VMware con la panoramica NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteggi le tue VM e i tuoi datastore VMware con NetApp Backup and Recovery. NetApp Backup and Recovery offre operazioni di backup e ripristino rapide, efficienti in termini di spazio, crash-consistent e VM-consistent. Puoi eseguire il backup dei carichi di lavoro VMware verso destinazioni di backup supportate e ripristinare i carichi di lavoro VMware su un host VMware on-premises.


NOTE: Questa versione di NetApp Backup and Recovery supporta solo VMware vCenter e non rileva vVols o VM su vVols.

Utilizza NetApp Backup and Recovery per implementare una strategia 3-2-1, in cui hai 3 copie dei tuoi dati di origine su 2 sistemi di archiviazione diversi, oltre a 1 copia nel cloud. I vantaggi dell'approccio 3-2-1 includono:

* Più copie di dati proteggono dalle minacce informatiche interne ed esterne.
* L'utilizzo di diversi tipi di supporto aiuta a recuperare i dati se un tipo non funziona.
* È possibile ripristinare rapidamente dalla copia in loco e utilizzare le copie fuori sede se la copia in loco è compromessa.


È possibile utilizzare NetApp Backup and Recovery per eseguire le seguenti attività relative ai carichi di lavoro VMware:

* link:br-use-vmware-discovery.html["Scopri i carichi di lavoro VMware"]
* link:br-use-vmware-protection-groups.html["Crea e gestisci gruppi di protezione per carichi di lavoro VMware"]
* link:br-use-vmware-backup.html["Eseguire il backup dei carichi di lavoro VMware"]
* link:br-use-vmware-restore.html["Ripristinare i carichi di lavoro VMware"]

