---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Proteggi i dati delle tue applicazioni Microsoft SQL Server dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure o StorageGRID utilizzando NetApp Backup and Recovery. 
---
= Proteggi i carichi di lavoro Microsoft SQL utilizzando la panoramica NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esegui il backup dei dati delle applicazioni Microsoft SQL Server dai sistemi ONTAP locali ad AWS, Azure o StorageGRID utilizzando NetApp Backup and Recovery.  Il sistema crea e archivia automaticamente i backup nel tuo account cloud, in base alle tue policy.  Utilizza una strategia 3-2-1: conserva tre copie dei tuoi dati su due sistemi di archiviazione e una copia nel cloud.

I vantaggi dell'approccio 3-2-1 includono:

* Più copie di dati proteggono dalle minacce informatiche interne ed esterne.
* L'utilizzo di diversi tipi di supporto aiuta a recuperare i dati se un tipo non funziona.
* È possibile ripristinare rapidamente dalla copia in loco e utilizzare le copie fuori sede se la copia in loco è compromessa.


NetApp Backup and Recovery utilizza NetApp SnapMirror per sincronizzare i backup creando copie snapshot e trasferendole nelle posizioni di backup.

Per proteggere i tuoi dati puoi fare quanto segue:

* link:concept-start-prereq-snapcenter-import.html["Configurare elementi aggiuntivi se si importa da SnapCenter"]
* link:br-start-discover.html["Scopri i carichi di lavoro di Microsoft SQL Server e, facoltativamente, importa le risorse SnapCenter"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro con snapshot locali sullo storage primario ONTAP locale"]
* link:br-use-mssql-backup.html["Replicare i carichi di lavoro sullo storage secondario ONTAP"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro in una posizione di archiviazione oggetti"]
* link:br-use-mssql-backup.html["Esegui subito il backup dei carichi di lavoro"]
* link:br-use-mssql-restore-overview.html["Ripristinare i carichi di lavoro"]
* link:br-use-mssql-clone.html["Clonazione dei carichi di lavoro"]
* link:br-use-manage-inventory.html["Gestire l'inventario dei carichi di lavoro"]
* link:br-use-manage-snapshots.html["Gestisci gli snapshot"]


Per eseguire il backup dei carichi di lavoro, è necessario creare policy che gestiscano le operazioni di backup e ripristino. Vederelink:br-use-policies-create.html["Creare politiche"] per maggiori informazioni.

.Destinazioni di backup supportate
NetApp Backup and Recovery consente di eseguire il backup di istanze e database di Microsoft SQL Server dai seguenti sistemi di origine ai seguenti sistemi secondari e storage di oggetti nei provider di cloud pubblici e privati.  Le copie snapshot risiedono sul sistema di origine.

[cols="33,33,33"]
|===
| Sistema sorgente | Sistema secondario (Replicazione) | Archivio oggetti di destinazione (backup) 


| Cloud Volumes ONTAP in AWS | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP in Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Azure Blob ONTAP S3 


| Sistema ONTAP in sede | Cloud Volumes ONTAP Sistema ONTAP locale | Blob di Azure Amazon S3 NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA ifdef::gcp[] endif::gcp[] ifdef::gcp[] endif::gcp[] 
|===
.Destinazioni di ripristino supportate
È possibile ripristinare istanze e database di Microsoft SQL Server da un backup che risiede nell'archivio primario o in un sistema secondario (un volume replicato) o nell'archivio oggetti (un file di backup) nei seguenti sistemi.  Le copie snapshot risiedono sul sistema di origine e possono essere ripristinate solo su quello stesso sistema.

[cols="33,33,33"]
|===
2+| Dalla posizione del file di backup | Al sistema di destinazione 


| *Archivio oggetti (backup)* | *Sistema secondario (replicazione)* |  


| Amazon S3 | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Cloud Volumes nel sistema ONTAP locale AWS ONTAP S3 


| Blob azzurro | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure ONTAP S3 ifdef::gcp[] endif::gcp[] 


| StorageGRID | Cloud Volumes ONTAP Sistema ONTAP locale | Sistema ONTAP on-premise ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===

NOTE: I riferimenti ai "sistemi ONTAP locali" includono i sistemi FAS e AFF .
