---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: 'Crea manualmente backup su richiesta delle applicazioni Kubernetes utilizzando l"interfaccia web NetApp Backup and Recovery.' 
---
= Esegui il backup di un'applicazione Kubernetes usando l'interfaccia web di NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizza l'interfaccia web per eseguire un backup su richiesta di un'applicazione Kubernetes.

*Ruolo richiesto NetApp Console*

Super admin di NetApp Backup and Recovery o backup admin di NetApp Backup and Recovery. link:reference-roles.html["Scopri di più sui ruoli di accesso a NetApp Backup and Recovery"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].



[[back-up-a-kubernetes-application]]
== Esegui il backup di un'applicazione Kubernetes

Crea manualmente un backup di un'applicazione Kubernetes per stabilire una base di riferimento per backup e snapshot futuri o per garantire la protezione dei dati più recenti.

.Passi
. In NetApp Backup and Recovery, seleziona *Inventario*.
. Scegli un'istanza Kubernetes e seleziona *Visualizza* per accedere alle risorse associate a quell'istanza.
. Selezionare la scheda *Applicazioni*.
. Nell'elenco delle applicazioni, seleziona un'applicazione di cui vuoi eseguire il backup e scegli il menu Azioni associato.
. Seleziona *Esegui backup ora*.
. Conferma che l'applicazione corretta sia selezionata.
. Selezionare *Backup*.


.Risultato
La Console crea un backup dell'applicazione e visualizza l'avanzamento nell'area *Monitoraggio* di Backup e Ripristino. Il backup viene creato in base ai criteri di protezione associati all'applicazione.
