---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i carichi di lavoro del tuo database Oracle con NetApp Backup and Recovery. 
---
= Ripristina i carichi di lavoro del database Oracle con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ripristina i carichi di lavoro di database Oracle da Snapshot, backup replicati su storage secondario o backup archiviati in storage a oggetti utilizzando NetApp Backup and Recovery.

.Ripristina da queste posizioni
È possibile ripristinare i database da diverse posizioni di partenza:

* Ripristina da una posizione primaria (snapshot locale)
* Ripristina da una risorsa replicata su un archivio secondario
* Ripristina da un backup di archiviazione di oggetti


.Ripristinare questi punti
È possibile ripristinare i dati nella posizione originale; il ripristino in una posizione alternativa non è disponibile in questa versione di anteprima privata.

* Ripristina la posizione originale




[[how-oracle-database-restore-works]]
== Come funziona il ripristino del database Oracle

Quando ripristini i carichi di lavoro del database Oracle, succede quanto segue:

* Quando si ripristina un database da uno snapshot locale, NetApp Backup and Recovery crea una _nuova_ risorsa utilizzando i dati del backup.
* Quando si esegue il ripristino da un archivio replicato, è possibile ripristinarlo nella posizione originale.
* Quando si ripristina un backup da un archivio oggetti, è possibile ripristinare i dati nell'archivio di origine o in un sistema ONTAP locale e recuperare il database da lì.


Dalla pagina Ripristina (nota anche come Cerca e ripristina), puoi ripristinare un database anche se non ricordi il nome esatto, la posizione in cui si trova o la data dell'ultima volta in cui era in buone condizioni.  È possibile effettuare ricerche nel database utilizzando i filtri.



[[restore-an-oracle-database]]
== Ripristinare un database Oracle

A seconda delle tue esigenze, puoi ripristinare un database Oracle a un punto specifico nel tempo, a uno specifico numero di modifica del sistema (SCN) o all'ultimo stato valido. Puoi anche ripristinare il database da Snapshot e saltare il processo di ripristino automatico, ad esempio se vuoi eseguire il ripristino manualmente. Puoi cercare il database utilizzando il suo nome o con filtri specifici.

*Ruolo richiesto NetApp Console* Super amministratore di Backup e ripristino o amministratore di ripristino di Backup e ripristino. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^]

.Passi
. Dal menu NetApp Console , selezionare *Protezione > Backup e ripristino*.
. Dal menu NetApp Backup and Recovery , selezionare *Ripristina*.
. Dall'elenco a discesa a destra del campo di ricerca del nome, seleziona *Oracle*.
. Immettere il nome del database che si desidera ripristinare oppure filtrare in base all'host del database in cui si trova il database che si desidera ripristinare.
+
Viene visualizzato un elenco di snapshot che corrispondono ai criteri di ricerca.

. Selezionare il pulsante *Ripristina* per il database che si desidera ripristinare.
. Scegli un'opzione di ripristino:
+
[role="tabbed-block"]
====
.Ripristinare un punto specifico nel tempo
--
.. Seleziona *Ripristina a un punto specifico nel tempo*.
.. Selezionare *Avanti*.
.. Scegli una data dal menu a discesa e seleziona *Cerca*.
+
Viene visualizzato un elenco di snapshot corrispondenti alla data specificata.



--
.Ripristinare un numero di modifica del sistema specifico (SCN)
--
.. Selezionare *Ripristina a un numero di modifica del sistema (SCN) specifico*.
.. Selezionare *Avanti*.
.. Inserisci l'SCN da utilizzare come punto di ripristino e seleziona *Cerca*.
+
Viene visualizzato un elenco di snapshot corrispondenti per l'SCN specificato.



--
.Ripristina l'ultimo backup (ultimo stato valido)
--
.. Seleziona *Ripristina all'ultimo backup*.
.. Selezionare *Avanti*.
+
Vengono visualizzati gli ultimi backup completi e di registro.



--
.Ripristina da snapshot senza recupero
--
.. Seleziona *Ripristina da snapshot senza ripristino*.
.. Selezionare *Avanti*.
+
Vengono visualizzate le istantanee corrispondenti.



--
====
. Selezionare una posizione di origine dello snapshot.
. Selezionare *Avanti* per continuare.
. Scegli la destinazione e le impostazioni di ripristino:


[discrete]
===== Selezione della destinazione

[role="tabbed-block"]
====
.Ripristina nella posizione originale
--
. *Impostazioni di destinazione*:
+
** Scegliere se ripristinare l'intero database o solo i tablespace del database.
** *File di controllo*: facoltativamente, abilitare questa opzione per ripristinare anche i file di controllo del database.


. *Opzioni pre-ripristino*:
+
** Facoltativamente, abilitare questa opzione e immettere il percorso completo di uno script che deve essere eseguito prima dell'operazione di ripristino e tutti gli argomenti accettati dallo script.
** Scegli un valore di timeout per lo script. Se lo script non viene eseguito entro questo periodo di tempo, il ripristino procede comunque.


. *Opzioni post-ripristino*:
+
** *Postscript*: facoltativamente, abilitare questa opzione e immettere il percorso completo di uno script che deve essere eseguito dopo l'operazione di ripristino e tutti gli argomenti accettati dallo script.
** *Apri il database o il container database in modalità LETTURA-SCRITTURA dopo il ripristino*: Al termine dell'operazione di ripristino, NetApp Backup and Recovery abilita la modalità LETTURA-SCRITTURA per il database.


. Sezione *Notifiche*:
+
** *Abilita notifiche e-mail*: seleziona questa opzione per ricevere notifiche e-mail sull'operazione di ripristino e indica il tipo di notifiche che desideri ricevere.


. Selezionare *Ripristina*.


--
.Ripristina in posizione alternativa
--
Non disponibile per i carichi di lavoro di database Oracle in questa versione di anteprima.

--
====