---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i tuoi carichi di lavoro KVM con NetApp Backup and Recovery. 
---
= Ripristinare le macchine virtuali KVM con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ripristina le macchine virtuali KVM da snapshot, da un backup del gruppo di protezione replicato su un archivio secondario o da backup archiviati nell'archivio oggetti utilizzando NetApp Backup and Recovery.

.Ripristina da queste posizioni
È possibile ripristinare le macchine virtuali da diverse posizioni di partenza:

* Ripristina da una posizione primaria (snapshot locale)
* Ripristina da una risorsa replicata su un archivio secondario
* Ripristina da un backup di archiviazione di oggetti


.Ripristinare questi punti
È possibile ripristinare i dati in questi punti:

* Ripristina la posizione originale
* Ripristina in una posizione alternativa


.Considerazioni sul ripristino da storage di oggetti
Se selezioni un file di backup in storage a oggetti e la protezione anti-ransomware è attiva per tale backup (se hai abilitato Datalock e la protezione anti-ransomware nella policy di backup), ti verrà richiesto di eseguire un ulteriore controllo di integrità sul file di backup prima di ripristinare i dati. Ti consigliamo di eseguire la scansione.


TIP: Per accedere al contenuto del file di backup, dovrai sostenere costi di uscita aggiuntivi da parte del tuo provider cloud.



== Come funziona il ripristino delle macchine virtuali

Quando si ripristinano macchine virtuali, si verifica quanto segue:

* Quando si ripristina un carico di lavoro da un file di backup locale, NetApp Backup and Recovery crea una _nuova_ risorsa utilizzando i dati del backup.
* Quando si esegue il ripristino da una VM replicata, è possibile ripristinarla nel sistema originale o in un sistema ONTAP locale.
* Quando si ripristina un backup da un archivio di oggetti, è possibile ripristinare i dati nel sistema originale o in un sistema ONTAP locale.


Dalla pagina Ripristina, puoi ripristinare una macchina virtuale anche se non ricordi il nome esatto, la posizione in cui si trova o la data dell'ultimo funzionamento corretto. Puoi cercare lo snapshot utilizzando i filtri.



== Ripristinare le macchine virtuali KVM

Ripristina le macchine virtuali KVM utilizzando il menu Ripristina. Puoi cercare lo snapshot per nome o utilizzando i filtri.

*Ruolo di console obbligatorio* Ruolo di super amministratore di Backup e ripristino o di amministratore di ripristino di Backup e ripristino. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .

.Passi
. Dal menu NetApp Console , selezionare *Protezione > Backup e ripristino*.
. Dal menu NetApp Backup and Recovery , selezionare *Ripristina*.
. Dall'elenco a discesa a destra del campo di ricerca del nome, selezionare *KVM*.
. Immettere il nome della macchina virtuale che si desidera ripristinare oppure filtrare in base all'host della macchina virtuale o al pool di archiviazione in cui si trova la risorsa da ripristinare.
+
Viene visualizzato un elenco di snapshot che corrispondono ai criteri di ricerca.

. Selezionare il pulsante *Ripristina* per lo snapshot che si desidera ripristinare.
+
Viene visualizzato un elenco di possibili punti di ripristino.

. Seleziona il punto di ripristino che desideri utilizzare.
. Selezionare una posizione di origine dello snapshot.
. Selezionare *Avanti* per continuare.
. Scegli la destinazione e le impostazioni di ripristino:
+
[discrete]
===== Selezione della destinazione

+
[role="tabbed-block"]
====
.Ripristina nella posizione originale
--
.. Selezionare il riquadro *Posizione originale*.
.. Nella sezione *Opzioni post-ripristino*, abilita l'opzione *Riavvia macchina virtuale* per riavviare la VM al termine dell'operazione di ripristino.


--
.Ripristina in posizione alternativa
--
.. Selezionare il riquadro *Posizione alternativa*.
.. Nella sezione *Impostazioni Cloudstack*: fornire le seguenti informazioni:
+
*** *Zona*: Scegli una zona CloudStack di destinazione dall'elenco.
*** *Pod*: Scegli un pod di destinazione all'interno della zona selezionata dall'elenco.
*** *Cluster*: Scegli un cluster di destinazione all'interno del pod selezionato dall'elenco.
*** *Host*: Scegliere un host di destinazione nel cluster dall'elenco.
*** *Pool di storage*: Scegli un pool di storage di destinazione dall'elenco (il volume di destinazione deve trovarsi qui).
*** *Rete*: Seleziona la rete a cui verrà connessa la macchina virtuale ripristinata.
*** *Nome VM*: Inserire un nome per la VM da ripristinare.
*** *Nome visualizzato*: immettere il nome che deve essere visualizzato per questa VM in Backup and Recovery.
*** *Percorso del pool di storage*: Inserire il percorso del pool di storage in cui verranno archiviati i volumi delle macchine virtuali.


.. Scegli un'offerta di servizi che definisca il livello di allocazione delle risorse che preferisci dall'elenco *Seleziona offerta di servizi*.
.. Abilita l'opzione *Forza* per importare la VM ripristinata anche se uno o più indirizzi MAC delle NIC della VM sono già presenti. Se un indirizzo MAC esiste già, viene generato un nuovo indirizzo MAC per quella NIC.
.. Nella sezione *Opzioni di ripristino post*, prendi in considerazione le seguenti opzioni:
+
*** *Riavvia la macchina virtuale*: Abilita questa opzione per avviare la nuova macchina virtuale dopo il ripristino.




--
====
. Selezionare *Ripristina*.

