---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: 'In NetApp Backup and Recovery, crea report per visualizzare lo stato dei tuoi backup, incluso il numero di backup, il numero di backup riusciti e il numero di backup non riusciti.  È inoltre possibile visualizzare i dettagli di ciascun backup, tra cui il tipo di backup, il sistema di archiviazione utilizzato per il backup e l"ora del backup.' 
---
= Crea report di protezione di Microsoft SQL Server in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crea report per i carichi di lavoro di Microsoft SQL Server in NetApp Backup and Recovery per esaminare lo stato e i dettagli dei backup, inclusi il numero di backup riusciti e non riusciti, i tipi di backup, i sistemi di storage e i timestamp.



[[create-a-protection-report]]
== Crea un report di protezione

*Ruolo NetApp Console richiesto* super admin di Backup and Recovery, backup admin di Backup and Recovery, restore admin di Backup and Recovery, clone admin di Backup and Recovery. Se stai proteggendo i dati memorizzati su un cluster Cloud Volumes ONTAP, è richiesto anche il ruolo Cloud Volumes ONTAP Admin. Scopri di più su link:reference-roles.html["Ruoli e privilegi di backup e ripristino"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^].

.Passi
. Dal menu NetApp Backup e ripristino, seleziona *Report*.
. Seleziona *Crea report*.
. Inserisci i dettagli dell'ambito del report:
+
** *Nome del report*: immettere un nome univoco per il report.
** *Tipo di report*: scegli se desideri un report per account o per carico di lavoro (Microsoft SQL Server).
** *Seleziona host*: se hai selezionato in base al carico di lavoro, seleziona l'host per il quale desideri generare il report.
** *Seleziona contenuto*: scegli se desideri che il report includa un riepilogo di tutti i backup o i dettagli di ciascun backup.  (Se hai scelto "Per account")


. Inserisci l'intervallo di riferimento: scegli se vuoi che il report includa i dati dell'ultimo giorno, degli ultimi 7 giorni, degli ultimi 30 giorni, dell'ultimo trimestre o dell'ultimo anno.
. Inserisci i dettagli per la consegna del report: se vuoi che il report venga inviato tramite email, seleziona *Invia report tramite email*. Inserisci l'indirizzo email a cui vuoi che venga inviato il report.
+
Configura le notifiche e-mail nella pagina Impostazioni. Per ulteriori dettagli sulla configurazione delle notifiche e-mail, consulta link:br-start-configure.html["Configurare le impostazioni"].


