---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: Proteggi i dati delle tue applicazioni Microsoft SQL Server dai sistemi ONTAP locali verso Amazon Web Services, Microsoft Azure o StorageGRID utilizzando NetApp Backup and Recovery. 
---
= Proteggi i carichi di lavoro di Microsoft SQL Server con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esegui il backup dei database di Microsoft SQL Server dai sistemi ONTAP locali su AWS, Azure o StorageGRID utilizzando NetApp Backup and Recovery. Implementa una strategia di backup 3-2-1 con Snapshot su storage primario, replica su storage secondario e copie su storage a oggetti.

NetApp Backup and Recovery utilizza NetApp SnapMirror per sincronizzare i backup creando snapshot e trasferendoli nelle posizioni di backup.

Utilizza i seguenti flussi di lavoro per proteggere i tuoi dati:

* link:concept-start-prereq-snapcenter-import.html["Configurare elementi aggiuntivi se si importa da SnapCenter"]
* link:br-start-discover.html["Scopri i carichi di lavoro di Microsoft SQL Server e, facoltativamente, importa le risorse SnapCenter"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro con snapshot locali sullo storage primario ONTAP locale"]
* link:br-use-mssql-backup.html["Replicare i carichi di lavoro sullo storage secondario ONTAP"]
* link:br-use-mssql-backup.html["Eseguire il backup dei carichi di lavoro in una posizione di archiviazione oggetti"]
* link:br-use-mssql-backup.html["Esegui subito il backup dei carichi di lavoro"]
* link:br-use-mssql-restore.html["Ripristinare i carichi di lavoro"]
* link:br-use-mssql-clone.html["Clonazione dei carichi di lavoro"]
* link:br-use-manage-inventory.html["Gestire l'inventario dei carichi di lavoro"]
* link:br-use-manage-snapshots.html["Gestisci gli snapshot"]


Per eseguire il backup dei carichi di lavoro, è necessario creare policy che gestiscano le operazioni di backup e ripristino. Vederelink:br-use-policies-create.html["Creare politiche"] per maggiori informazioni.

.Destinazioni di backup supportate
NetApp Backup e ripristino supporta il backup di istanze e database di Microsoft SQL Server dai seguenti sistemi di origine ai sistemi secondari e agli archivi di oggetti elencati nei cloud pubblici e privati. Gli Snapshot rimangono sul sistema di origine.

[cols="33,33,33"]
|===
| Sistema sorgente | Sistema secondario (replica) | archivio di oggetti (backup) 


| Cloud Volumes ONTAP in AWS | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP in Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Azure Blob ONTAP S3 


| Sistema ONTAP in sede | Cloud Volumes ONTAP Sistema ONTAP locale | Blob di Azure Amazon S3 NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===
.Destinazioni di ripristino supportate
Puoi ripristinare istanze e database di Microsoft SQL Server da un backup che si trova nello storage primario, in un sistema secondario (volume replicato) o nello storage a oggetti (file di backup) verso i seguenti sistemi di destinazione. Le Snapshot risiedono nel sistema di origine e possono essere ripristinate solo su quello stesso sistema.

[cols="33,33,33"]
|===
2+| Dalla posizione del file di backup | Al sistema di destinazione 


| *Archivio di oggetti (backup)* | *Sistema secondario (replica)* |  


| Amazon S3 | Cloud Volumes ONTAP nel sistema ONTAP locale di AWS | Cloud Volumes ONTAP in AWS Sistema ONTAP locale ONTAP S3 


| Blob azzurro | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure | Cloud Volumes ONTAP nel sistema ONTAP locale di Azure ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP Sistema ONTAP locale | Sistema ONTAP on-premise ONTAP S3 
|===

NOTE: I riferimenti ai "sistemi ONTAP locali" includono i sistemi FAS e AFF .
