---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-clusters.html 
keywords: discover, backup and recovery, snapcenter, kubernetes, k8s, clusters, applications, inventory 
summary: NetApp Backup and Recovery ti consente di scoprire e gestire i tuoi cluster Kubernetes in modo da poter proteggere le risorse ospitate dai cluster. 
---
= Gestire i cluster Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery ti consente di scoprire e gestire i tuoi cluster Kubernetes in modo da poter proteggere le risorse ospitate dai cluster.

.Ruolo richiesto NetApp Console
Amministratore dell'organizzazione o amministratore SnapCenter . link:reference-roles.html["Scopri di più sui ruoli di accesso a NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso NetApp Console per tutti i servizi"^] .


NOTE: Per scoprire i cluster Kubernetes, fare riferimento alink:br-start-discover.html["Scopri i carichi di lavoro di Kubernetes"] .



== Modifica le informazioni del cluster Kubernetes

È possibile modificare un cluster se è necessario cambiarne il nome.

.Passi
. In NetApp Backup and Recovery, seleziona *Inventario* > *Cluster*.
. Nell'elenco dei cluster, seleziona il cluster che desideri modificare e seleziona il menu Azioni associato.
. Seleziona *Modifica cluster*.
. Apportare le modifiche necessarie al nome del cluster. Il nome del cluster deve corrispondere al nome utilizzato con il comando Helm durante il processo di individuazione.
. Selezionare *Fatto*.




== Rimuovere un cluster Kubernetes

Per interrompere la protezione di un cluster Kubernetes, disabilitare la protezione ed eliminare le applicazioni associate, quindi rimuovere il cluster da NetApp Backup and Recovery.  NetApp Backup and Recovery non elimina il cluster o le sue risorse; rimuove solo il cluster dall'inventario della NetApp Console .

.Passi
. In NetApp Backup and Recovery, seleziona *Inventario* > *Cluster*.
. Nell'elenco dei cluster, seleziona il cluster che desideri modificare e seleziona il menu Azioni associato.
. Selezionare *Rimuovi cluster*.
. Rivedi le informazioni nella finestra di dialogo di conferma e seleziona *Rimuovi*.

