---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: È possibile proteggere le macchine virtuali Oracle dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID, garantendo la protezione dei dati. 
---
= Proteggi i carichi di lavoro del database Oracle con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Usa NetApp Backup and Recovery per proteggere i carichi di lavoro e i log di database Oracle con backup e ripristini rapidi, efficienti in termini di spazio, coerenti con il crash e coerenti con il database. Puoi eseguire il backup dei carichi di lavoro su Amazon S3, StorageGRID, Azure Blob o ONTAP S3 e ripristinare i backup su un host Oracle on-premises.

Utilizza NetApp Backup and Recovery per implementare una strategia di protezione 3-2-1, in cui hai 3 copie dei tuoi dati di origine su 2 sistemi di archiviazione diversi, oltre a 1 copia nel cloud. I vantaggi dell'approccio 3-2-1 includono:

* Più copie di dati proteggono dalle minacce informatiche interne ed esterne.
* L'utilizzo di diversi tipi di supporto aiuta a recuperare i dati se un tipo non funziona.
* È possibile ripristinare rapidamente dalla copia in loco e utilizzare le copie fuori sede se la copia in loco è compromessa.


È possibile utilizzare NetApp Backup and Recovery per eseguire le seguenti attività relative ai carichi di lavoro di Oracle Database:

* link:br-start-discover-oracle.html["Scopri i carichi di lavoro Oracle Database"]
* link:br-use-oracle-protection-groups.html["Gestisci i gruppi di protezione per i carichi di lavoro di Oracle Database"]
* link:br-use-oracle-backup.html["Esegui il backup dei carichi di lavoro Oracle Database"]
* link:br-use-oracle-clone.html["Clona i carichi di lavoro del database Oracle"]
* link:br-use-oracle-restore.html["Ripristina i carichi di lavoro del database Oracle"]

