---
sidebar: sidebar 
permalink: br-use-kvm-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: È possibile proteggere le macchine virtuali KVM dai sistemi ONTAP locali ad Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID, garantendo la protezione dei dati. 
---
= Flusso di lavoro di protezione KVM con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteggi le tue VM KVM gestite e i pool di storage con NetApp Backup and Recovery. Il servizio offre operazioni di backup e ripristino rapide, efficienti in termini di spazio, coerenti in caso di arresto anomalo e coerenti con le VM.

I tuoi host KVM e le VM devono essere gestiti da una piattaforma come Apache CloudStack prima che tu possa proteggerli con NetApp Backup and Recovery.

Utilizza NetApp Backup and Recovery per implementare una strategia di protezione 3-2-1, in cui hai 3 copie dei tuoi dati di origine su 2 sistemi di archiviazione diversi, oltre a 1 copia nel cloud. I vantaggi dell'approccio 3-2-1 includono:

* Più copie di dati proteggono dalle minacce informatiche interne ed esterne.
* L'utilizzo di diversi tipi di supporti ti aiuta a recuperare i dati se uno di essi si guasta.
* È possibile ripristinare rapidamente dalla copia in loco e utilizzare le copie fuori sede se la copia in loco è compromessa.


Puoi usare NetApp Backup e ripristino per eseguire le seguenti attività per i carichi di lavoro KVM:

* link:br-start-discover-kvm.html["Scopri i carichi di lavoro KVM"]
* link:br-use-kvm-protection-groups.html["Crea e gestisci gruppi di protezione per carichi di lavoro KVM"]
* link:br-use-kvm-backup.html["Eseguire il backup dei carichi di lavoro KVM"]
* link:br-use-kvm-restore.html["Ripristinare i carichi di lavoro KVM"]

