---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 'Inizia a utilizzare NetApp Backup and Recovery verificando la prontezza del tuo ambiente operativo, dell"agente della console e dell"account della console.  Per utilizzare NetApp Backup and Recovery, sono necessari i seguenti prerequisiti.' 
---
= NetApp Backup and Recovery requisiti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di iniziare a utilizzare NetApp Backup and Recovery, assicurati che la NetApp Console e l'ambiente operativo soddisfino i seguenti requisiti.



== Preparare NetApp Console

È possibile accedere a NetApp Backup e Ripristino tramite NetApp Console. Per preparare la Console per Backup e Ripristino, è necessario:

* Aggiungi un agente della console
* Aggiungere almeno un sistema storage
* Configurare un'organizzazione Console e i ruoli utente


Per completare questa preparazione, è necessario disporre del ruolo di amministratore dell'organizzazione o di super amministratore nella NetApp Console.

Per ulteriori informazioni su NetApp Console, fare riferimento a  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console per la gestione unificata dello storage"^].



=== Completa la configurazione iniziale della NetApp Console

Completa la configurazione iniziale di NetApp Console se non l'hai già fatto.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flusso di lavoro introduttivo per NetApp Console (applicazione SaaS)"^]



=== Distribuisci un agente della Console

Un agente Console è un componente software leggero che si installa nella rete per connettere l'infrastruttura di storage a NetApp Console. Consente l'orchestrazione avanzata dello storage, i servizi dati e l'integrazione sicura con il cloud.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Scopri di più sugli agenti della console"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Distribuisci un agente della Console"^]



=== Aggiungi un sistema storage

Prima di poter proteggere i carichi di lavoro in NetApp Backup and Recovery, è necessario aggiungere un sistema storage ONTAP alla NetApp Console.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Scopri i cluster ONTAP on-premises in NetApp Console"^]



=== Configurare un'organizzazione e i ruoli utente

Acquisisci informazioni su organizzazioni, progetti e ruoli utente, quindi configura gli utenti con le autorizzazioni appropriate necessarie per svolgere i loro compiti.

Consultare  https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["Aggiungere utenti a un'organizzazione NetApp Console"] per informazioni sull'utilizzo di un'organizzazione e di progetti per il controllo dell'accesso alle risorse.

Consultare  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Ruoli NetApp Backup and Recovery nella NetApp Console"] per i dettagli sui ruoli e le autorizzazioni necessari per eseguire operazioni in NetApp Backup and Recovery.



== Requisiti per i backup su storage a oggetti

Per utilizzare storage a oggetti come destinazione di backup, è necessario disporre di un account AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID o ONTAP e delle autorizzazioni di accesso appropriate configurate.



== Requisiti per la protezione dei carichi di lavoro dei volumi ONTAP

Per utilizzare NetApp Backup e ripristino per i carichi di lavoro dei volumi ONTAP, sono necessari i seguenti prerequisiti relativi al sistema host, allo spazio e alle dimensioni.

* È richiesto ONTAP 9.8 o versioni successive.
* Sull'istanza ONTAP locale deve essere abilitata una licenza ONTAP One.
* Per eseguire il backup o il ripristino su storage a oggetti compatibile con S3 è necessario ONTAP 9.17.1 o versioni successive.


Per informazioni sulle funzionalità supportate, i tipi di volume, le destinazioni di backup e ripristino e altro ancora, fare riferimento a link:prev-ontap-protect-overview.html["Proteggi i dati del tuo volume ONTAP"].



== Requisiti per la protezione dei carichi di lavoro di Microsoft SQL Server

Per utilizzare NetApp Backup and Recovery per i carichi di lavoro di Microsoft SQL Server, sono necessari i seguenti prerequisiti relativi a sistema host, spazio e dimensionamento.

[cols="33,66a"]
|===
| Articolo | Requisiti 


| Sistemi operativi  a| 
Microsoft Windows Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Strumento matrice di interoperabilità NetApp"^] .



| Versioni di Microsoft SQL Server  a| 
Le versioni 2012 e successive sono supportate per VMware Virtual Machine File System (VMFS) e VMware Virtual Machine Disk (VMDK) NFS.



| Versione di SnapCenter Server  a| 
Per importare i dati esistenti da SnapCenter in NetApp Backup and Recovery è necessario SnapCenter Server versione 5.0 o successiva.


NOTE: Se hai già SnapCenter, verifica innanzitutto di aver soddisfatto i prerequisiti prima di importare da SnapCenter.  Vederelink:concept-start-prereq-snapcenter-import.html["Prerequisiti per l'importazione di risorse da SnapCenter"] .



| RAM minima per il plug-in sull'host SQL Server  a| 
1 GB



| Spazio minimo di installazione e di registro per il plug-in sull'host SQL Server  a| 
5 GB

Assegnare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di backup eseguiti e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente, i log per le operazioni non verranno creati.



| Pacchetti software richiesti  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle (e tutte le patch 8.0.x successive)
* PowerShell 7.4.13


Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Strumento matrice di interoperabilità NetApp"^] .

|===
[cols="33,66a"]
|===
| Host del database | Storage supportati 


| Server fisico  a| 
* LUN presentate tramite Fibre Channel
* LUN presentati tramite iSCSI




| VMware VM  a| 
* LUN iSCSI connessi direttamente al sistema guest tramite l'iSCSI initiator
* File system per macchine virtuali (VMFS)
* Datastore NFS




| Macchina virtuale Hyper-V  a| 
LUN iSCSI connessi direttamente al sistema guest tramite l'iSCSI initiator


NOTE: La protezione dei database memorizzati in dischi pass-through o file VHD/VHDX di cui è stato effettuato il provisioning su storage NetApp non è supportata.

|===


== Requisiti per la protezione dei carichi di lavoro VMware

Per individuare e proteggere i carichi di lavoro VMware sono necessari requisiti specifici.

|===
| Requisito | Supportato 


| Tipi di datastore | NFSv3, NFSv4.1 e VMFS 


| Versioni di VMware ESXi Server | 7.0U1 e versioni successive 


| Versioni VMware vCenter vSphere | 7.0U1 e versioni successive 


| VMware Tools | VMware Tools è necessario quando si utilizza la funzionalità di ripristino di file e cartelle e i backup coerenti con la macchina virtuale. Per assicurarsi che la versione di VMware Tools corrisponda alla versione di ESXi Server in uso, fare riferimento a  https://packages.vmware.com/tools/versions["Informazioni sulla mappatura delle versioni di VMware"]. 


| Tipi di indirizzo IP | IPv4, IPv6 


| Versioni TLS di VMware | 1.2, 1.3 


| Archiviazione connessa  a| 
* ONTAP 9.13.1 o successivo
* Amazon FSx for NetApp ONTAP storage systems che eseguono la versione 9.13.1 o successiva
* ASA r2 sistemi solo SAN (ONTAP 9.17.1 o versioni successive richieste)


|===
[cols="33,66a"]
|===
| Tipo di porto | Porta preconfigurata 


| Porta del server VMware ESXi  a| 
443 (HTTPS), bidirezionale. La funzione di ripristino di file e cartelle utilizza questa porta.



| Cluster di archiviazione o porta VM di archiviazione  a| 
* 443 (HTTPS), bidirezionale.
* 80 (HTTP), bidirezionale. Questa porta viene utilizzata per la comunicazione tra l'appliance virtuale e la VM di storage o il cluster che contiene la VM di storage.


|===
.Requisiti di controllo degli accessi basato sui ruoli (RBAC) per la protezione dei carichi di lavoro VMware
Il tuo account utente della Console deve disporre del ruolo di super amministratore di NetApp Backup and Recovery per poter lavorare con i carichi di lavoro VMware.

Per ulteriori informazioni sui ruoli di Backup e Recovery, fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Ruoli di backup e ripristino nella NetApp Console"].



== Requisiti per la protezione dei carichi di lavoro KVM

Per individuare e proteggere le macchine virtuali KVM sono necessari requisiti specifici.

* Una moderna distribuzione Linux che esegue la versione del kernel 5.14.0-503.22.1.el9_5.x86_64 (a lungo termine) o successiva
* Gli host KVM e le VM devono essere gestiti da una piattaforma di gestione. NetApp Backup and Recovery supporta le seguenti piattaforme di gestione:
+
** Apache CloudStack 4.22.0.0


* Assicurarsi che il traffico di rete in entrata sulla porta 22 sia consentito dall'agente della console all'host KVM
* QEMU Guest Agent versione 9.0.0 o successiva
* libvirt versione 10.5.0 o successiva



NOTE: Per garantire che i ripristini del carico di lavoro KVM vengano completati correttamente, accertarsi che l'impostazione *Abilita snapshot coerente con la VM* sia attiva nel criterio di protezione utilizzato per i backup KVM.

[NOTE]
====
Per abilitare la protezione delle VM KVM amministrate da utenti non root, attenersi alla seguente procedura:

. Montare il volume come tipo NFS3 per evitare l'uso del `nobody` utente e gruppo.
. Utilizzare il seguente comando per aggiungere un utente non root al `qemu` gruppo pur preservando i loro gruppi esistenti:
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. Utilizzare il seguente comando per concedere la proprietà del percorso di montaggio al `qemu` utente e gruppo e modifica i permessi per il percorso di montaggio:
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Eliminare la directory NetApp_SnapCenter_Backups esistente, se presente.


====


== Requisiti per la protezione dei carichi di lavoro Oracle Database

Assicurati che il tuo ambiente soddisfi requisiti specifici per individuare e proteggere le risorse Oracle Database.

|===
| Requisito | Supportato 


| Topologia di distribuzione  a| 
* Autonomo (NFS, SAN, ASM SAN)
* RAC su ASM (VMDK su VMFS)




| Versioni di Oracle Database  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| Archiviazione del database | Deve essere distribuito su NetApp ONTAP (primario o secondario) 


| OS dell'host  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| Object storage (destinazioni di backup)  a| 
* Archiviazione oggetti di Azure
* Amazon AWS
* NetApp StorageGRID
* ONTAP S3


|===


== Requisiti per la protezione delle applicazioni Kubernetes

Per scoprire le risorse di Kubernetes e proteggere le applicazioni Kubernetes, sono necessari requisiti specifici.

Per i requisiti NetApp Console , fare riferimento a<<In NetApp Console>> .


NOTE: NetApp raccomanda vivamente di assegnare un indirizzo IP statico all'agente della Console utilizzato per i carichi di lavoro Kubernetes, per evitare problemi se l'indirizzo IP dell'agente cambia.

* Un sistema ONTAP primario (i sistemi ASA r2 non sono supportati)
* NetApp Trident 25.02 o versioni successive
* NetApp Trident Protect 26.05 o versioni successive (installato sul cluster Kubernetes durante la fase di rilevamento)
* Un cluster Kubernetes - Le distribuzioni e le versioni di Kubernetes supportate includono quelle supportate da  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"].
+
** Assicurarsi che la porta TCP 443 non sia filtrata in direzione outbound tra il cluster Kubernetes, il Trident Protect Connector e il Trident Protect proxy.






== Requisiti per la protezione dei carichi di lavoro Hyper-V

Assicurati che la tua istanza Hyper-V soddisfi requisiti specifici per individuare e proteggere le macchine virtuali.

|===
| Requisito | Supportato 


| Microsoft Hyper-V | 2019, 2022 e 2025 editions 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle (e tutte le successive patch 8.0.x) 


| PowerShell | 7.4.13 o versioni successive 


| Se gli utenti non amministratori proteggeranno le VM Hyper-V, assicurarsi che dispongano delle seguenti autorizzazioni  a| 
* Membro del gruppo degli amministratori locali
* Parte della policy di sicurezza locale "Log on as service"




| Assicurarsi che il traffico HTTPS bidirezionale sia consentito per le seguenti porte nelle impostazioni del Windows Firewall  a| 
* TCP 8144 (NetApp Plugin per Hyper-V)
* TCP 8145 (NetApp Plugin per Windows)




| Archiviazione connessa  a| 
* ONTAP 9.13.1 o successivo
* Amazon FSx for NetApp ONTAP storage systems che eseguono la versione 9.13.1 o successiva
* Archiviazione SAN (supportata per backup e per il ripristino nella posizione originale sia da storage primario che da storage secondario)


|===
.Requisiti hardware per l'host Hyper-V
* Sono supportati host autonomi e in cluster FCI
* Almeno 1 GB di RAM per il plug-in NetApp Hyper-V sull'host Hyper-V
* Spazio minimo di installazione e registro di 5 GB per il plug-in sull'host Hyper-V
+

NOTE: Assicurarsi di allocare spazio su disco sufficiente sull'host Hyper-V per la cartella dei registri e monitorarne regolarmente l'utilizzo.  Lo spazio necessario dipende dalla frequenza con cui si verificano i backup e le operazioni di protezione dei dati.  Se lo spazio non è sufficiente, i registri non verranno generati.



.NetApp Requisiti di configurazione ONTAP
* Un sistema ONTAP primario (ONTAP 9.14.1 o successivo)
* Per le distribuzioni Hyper-V che utilizzano condivisioni CIFS per archiviare i dati delle macchine virtuali, assicurarsi che la proprietà di condivisione della disponibilità continua sia abilitata sul sistema ONTAP .  Fare riferimento al https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["Documentazione ONTAP"^] per istruzioni.

