---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery supporta una classe di archiviazione Google e la maggior parte delle regioni. 
---
= Livelli di archiviazione di Google supportati con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizza queste informazioni per comprendere il livello di archiviazione di Google Cloud Storage che NetApp Backup and Recovery supporta. Puoi anche verificare i costi di ripristino e i tempi di recupero per i backup archiviati.



[[supported-google-archival-storage-classes-for-netapp-backup-and-recovery]]
== Classi di archiviazione Google supportate per NetApp Backup and Recovery

Quando i file di backup vengono creati inizialmente, vengono archiviati nello storage _Standard_. Questo livello è ottimizzato per l'archiviazione di dati a cui si accede raramente, ma consente comunque l'accesso immediato.

Se il tuo cluster on-premises utilizza ONTAP 9.12.1 o versioni successive, puoi scegliere di spostare i backup meno recenti nello storage _Archive_ nell'interfaccia utente di NetApp Backup and Recovery dopo un certo numero di giorni (di solito più di 30 giorni) per ottimizzare ulteriormente i costi. I dati in questo tier avranno un costo di recupero più elevato, quindi devi considerare quanto spesso potresti aver bisogno di ripristinare dati da questi file di backup archiviati. Vedi la sezione in questa pagina sul ripristino dei dati dallo storage di archiviazione.

Tieni presente che quando configuri NetApp Backup and Recovery con questo tipo di regola del ciclo di vita, non devi configurare alcuna regola del ciclo di vita quando imposti il ​​bucket nel tuo account Google.

https://cloud.google.com/storage/docs/storage-classes["Scopri di più sulle classi di archiviazione di Google"^].



[[restore-data-from-archival-storage]]
== Ripristinare i dati dall'archivio

Sebbene l'archiviazione di file di backup più vecchi in un archivio sia molto meno costosa rispetto all'archiviazione standard, l'accesso ai dati da un file di backup in un archivio per le operazioni di ripristino richiederà un tempo leggermente più lungo e avrà un costo maggiore.

Quanto costa ripristinare i dati da Google Archive?:: Per i prezzi dettagliati di Google Cloud Storage per regione, visita https://cloud.google.com/storage/pricing["Pagina dei prezzi di Google Cloud Storage"^] .
Quanto tempo ci vorrà per ripristinare i miei oggetti archiviati in Google Archive?:: Il tempo totale di ripristino è composto da 2 parti:
+
--
* *Tempo di recupero*: tempo necessario per recuperare il file di backup dall'archivio e posizionarlo nell'archiviazione standard.  Questo è talvolta chiamato il periodo di "reidratazione".  A differenza delle soluzioni di archiviazione "più fredde" offerte da altri provider cloud, i tuoi dati sono accessibili in pochi millisecondi.
* *Tempo di ripristino*: tempo necessario per ripristinare i dati dal file di backup nell'archiviazione standard.  Questa volta non c'è differenza rispetto alla tipica operazione di ripristino eseguita direttamente dall'archiviazione Standard, quando non si utilizza un livello di archiviazione.


--

