---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i tuoi carichi di lavoro VMware con NetApp NetApp Backup and Recovery. 
---
= Registra il SnapCenter Plug-in for VMware vSphere da utilizzare con NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario registrare il SnapCenter Plug-in for VMware vSphere in NetApp Backup and Recovery affinché i datastore e le macchine virtuali vengano visualizzati.  Solo un utente con accesso amministrativo può registrare il SnapCenter Plug-in for VMware vSphere .


NOTE: Per passare da e verso i carichi di lavoro NetApp Backup and Recovery , fare riferimento alink:br-start-switch-ui.html["Passa a diversi carichi di lavoro NetApp Backup and Recovery"] .

.Passi
. Nell'interfaccia utente NetApp Console , selezionare *Protezione* > *Backup e ripristino* > *Macchine virtuali*.
. Dal menu a discesa *Impostazioni*, seleziona * SnapCenter Plug-in for VMware vSphere*.
. Selezionare *Registra il SnapCenter Plug-in for VMware vSphere*.
. Specificare i seguenti dettagli:
+
.. Nel campo SnapCenter Plug-in for VMware vSphere , specificare l'FQDN o l'indirizzo IP dell'host del SnapCenter Plug-in for VMware vSphere .
.. Nel campo Porta, specificare il numero di porta su cui è in esecuzione l'host SnapCenter Plug-in for VMware vSphere .
+
È necessario assicurarsi che la comunicazione sia aperta tra l'host SnapCenter Plug-in for VMware vSphere in locale, in esecuzione sulla porta predefinita 8144, e l'istanza dell'agente della console, che potrebbe essere in esecuzione su qualsiasi provider cloud (Amazon Web Services, Microsoft Azure, Google Cloud Platform) o in locale.

.. Nel campo Nome utente e password, specificare le credenziali dell'utente vCenter con ruolo di amministratore.


. Seleziona *Registrati*.


*Dopo aver finito*

Selezionare *Backup e ripristino* > *Macchine virtuali* per visualizzare tutti i datastore e le macchine virtuali protetti mediante il SnapCenter Plug-in for VMware vSphere .
