---
settings:
  name: NetApp Backup and Recovery
  release_notes_autogen:
    release_notes_repo: console-local-relnotes, console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione NetApp Backup and Recovery
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità in NetApp Backup and Recovery
      url: "/whats-new.html"
    - title: Limitazioni note per i carichi di lavoro dei volumi ONTAP
      url: "/br-reference-limitations.html"
    - title: Limitazioni note per i carichi di lavoro di SQL Server
      url: "/br-limitations.html"
    - title: Limitazioni note per i carichi di lavoro VMware
      url: "/br-limitations-vmware.html"
    - title: Limitazioni note per i carichi di lavoro Hyper-V
      url: "/br-limitations-hyperv.html"
    - title: Limitazioni note per i carichi di lavoro KVM
      url: "/br-limitations-kvm.html"
    - title: Limitazioni note per i carichi di lavoro di Oracle Database
      url: "/br-limitations-oracle.html"
  - title: Iniziare
    entries:
    - title: Scopri di più su NetApp Backup and Recovery
      url: "/concept-backup-to-cloud.html"
    - title: NetApp Backup and Recovery requisiti
      url: "/concept-start-prereq.html"
    - title: Configura le licenze
      url: "/br-start-licensing.html"
    - title: Configura i certificati di sicurezza
      url: "/task-setup-ca-certificates.html"
    - title: Configurare le destinazioni di backup prima di utilizzare NetApp Backup
        and Recovery
      url: "/br-start-setup.html"
    - title: Scopri le destinazioni di backup remote
      url: "/br-start-discover-backup-targets.html"
    - title: Passa a diversi carichi di lavoro NetApp Backup and Recovery
      url: "/br-start-switch-ui.html"
    - title: Configurare le impostazioni NetApp Backup and Recovery
      url: "/br-start-configure.html"
    - title: Configura il controllo degli accessi in base al ruolo
      url: "/br-rbac-setup.html"
  - title: Utilizzare NetApp Backup and Recovery
    entries:
    - title: Accedi a NetApp Backup and Recovery
      url: "/br-start-login.html"
    - title: Visualizza lo stato di protezione sulla dashboard di NetApp Backup and
        Recovery
      url: "/br-use-dashboard.html"
    - title: Proteggere i carichi di lavoro del volume ONTAP
      entries:
      - title: Scopri NetApp Backup and Recovery per i volumi ONTAP
        url: "/prev-ontap-protect-overview.html"
      - title: Abilita NetApp Backup and Recovery per proteggere i volumi
        url: "/br-start-enable.html"
      - title: Migliora le prestazioni di ricerca e ripristino nelle implementazioni
          locali di NetApp Backup and Recovery
        url: "/prev-ontap-protect-migrate-pvc.html"
      - title: Opzioni di pianificazione del percorso di protezione in NetApp Backup
          and Recovery
        url: "/prev-ontap-protect-journey.html"
      - title: Scopri sistemi e volumi ONTAP senza attivazione
        url: "/prev-ontap-discover-no-activate.html"
      - title: Gestisci le policy di backup per i volumi ONTAP
        url: "/prev-ontap-policy-manage.html"
      - title: Opzioni dei criteri di backup su oggetto dei volumi ONTAP
        url: "/prev-ontap-policy-object-options.html"
      - title: Gestisci le opzioni di backup su storage a oggetti
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Esegui il backup dei dati Cloud Volumes ONTAP su Amazon S3
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Esegui il backup dei dati di Cloud Volumes ONTAP nello storage Blob
          di Azure
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Esegui il backup dei dati di Cloud Volumes ONTAP su Google Cloud Storage
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: Eseguire il backup dei dati ONTAP locali su Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: Esegui il backup dei dati ONTAP on-premise nello storage Blob di Azure
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: Esegui il backup dei dati ONTAP on-premises su Google Cloud Storage
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: Eseguire il backup dei dati ONTAP locali su ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: Esegui il backup dei dati ONTAP on-premise su uno storage compatibile
          con S3
        url: "/prev-ontap-backup-onprem-s3-compatible.html"
      - title: Eseguire il backup dei dati ONTAP locali su StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: Migra i volumi ONTAP utilizzando SnapMirror su Cloud Resync
        url: "/prev-ontap-migrate-resync.html"
      - title: Gestisci i backup per i tuoi sistemi ONTAP
        url: "/prev-ontap-backup-manage.html"
      - title: Ripristina dai backup ONTAP
        entries:
        - title: Opzioni di ripristino dei dati ONTAP
          url: "/prev-ontap-restore.html"
        - title: Ripristina i dati ONTAP utilizzando Cerca e ripristina
          url: "/prev-ontap-restore-search.html"
        - title: Ripristina i dati ONTAP utilizzando Sfoglia e Ripristina
          url: "/prev-ontap-restore-browse.html"
    - title: Proteggere i carichi di lavoro di Microsoft SQL Server
      entries:
      - title: Flusso di lavoro di protezione di Microsoft SQL Server in NetApp Backup
          and Recovery
        url: "/br-use-mssql-protect-overview.html"
      - title: Prerequisiti di importazione di SnapCenter per NetApp Backup and Recovery
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Scopri i carichi di lavoro di Microsoft SQL Server
        url: "/br-start-discover.html"
      - title: Crea e gestisci le policy di backup di Microsoft SQL Server
        url: "/br-use-policies-mssql-create.html"
      - title: Eseguire il backup dei carichi di lavoro di Microsoft SQL Server
        url: "/br-use-mssql-backup.html"
      - title: Ripristinare i carichi di lavoro di Microsoft SQL Server
        url: "/br-use-mssql-restore.html"
      - title: Clonazione dei carichi di lavoro di Microsoft SQL Server
        url: "/br-use-mssql-clone.html"
      - title: Gestire l'inventario di Microsoft SQL Server
        url: "/br-use-manage-inventory.html"
      - title: Gestire gli snapshot di Microsoft SQL Server
        url: "/br-use-manage-snapshots.html"
      - title: Creare report di Microsoft SQL Server
        url: "/br-use-reports.html"
    - title: Proteggi i carichi di lavoro VMware
      entries:
      - title: Flusso di lavoro di protezione VMware
        url: "/br-use-vmware-protect-overview.html"
      - title: Scopri i carichi di lavoro VMware
        url: "/br-use-vmware-discovery.html"
      - title: Gestisci i gruppi di protezione VMware
        url: "/br-use-vmware-protection-groups.html"
      - title: Gestisci le policy di backup di VMware
        url: "/br-use-policies-vmware-create.html"
      - title: Eseguire il backup dei carichi di lavoro VMware
        url: "/br-use-vmware-backup.html"
      - title: Clonare i carichi di lavoro VMware
        url: "/br-use-vmware-clone.html"
      - title: Ripristinare i carichi di lavoro VMware
        entries:
        - title: Ripristinare i carichi di lavoro VMware
          url: "/br-use-vmware-restore.html"
        - title: Ripristina i dischi virtuali VMware dai backup
          url: "/br-use-vmware-restore-vmdks-from-backups.html"
        - title: Ripristinare file e cartelle VMware
          entries:
          - title: Requisiti per il ripristino dei file guest di VMware
            url: "/br-use-vmware-restore-guest-files-and-folders-overview.html"
          - title: Ripristina i file e le cartelle della macchina virtuale VMware
            url: "/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html"
          - title: Risoluzione dei problemi relativi al ripristino di file e cartelle
            url: "/br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html"
    - title: Proteggere i carichi di lavoro KVM
      entries:
      - title: Panoramica sulla protezione dei carichi di lavoro KVM
        url: "/br-use-kvm-protect-overview.html"
      - title: Scopri i carichi di lavoro KVM
        url: "/br-start-discover-kvm.html"
      - title: Crea e gestisci gruppi di protezione per carichi di lavoro KVM
        url: "/br-use-kvm-protection-groups.html"
      - title: Crea e gestisci le policy di backup dei carichi di lavoro KVM
        url: "/br-use-policies-kvm-create.html"
      - title: Eseguire il backup dei carichi di lavoro KVM
        url: "/br-use-kvm-backup.html"
      - title: Ripristinare i carichi di lavoro KVM
        url: "/br-use-kvm-restore.html"
    - title: Proteggere i carichi di lavoro Hyper-V
      entries:
      - title: Panoramica sulla protezione dei carichi di lavoro Hyper-V
        url: "/br-use-hyperv-protect-overview.html"
      - title: Scopri i carichi di lavoro Hyper-V
        url: "/br-start-discover-hyperv.html"
      - title: Crea e gestisci gruppi di protezione per carichi di lavoro Hyper-V
        url: "/br-use-hyperv-protection-groups.html"
      - title: Creare e gestire le policy di backup dei carichi di lavoro Hyper-V
        url: "/br-use-policies-hyper-v-create.html"
      - title: Eseguire il backup dei carichi di lavoro Hyper-V
        url: "/br-use-hyperv-backup.html"
      - title: Ripristinare i carichi di lavoro Hyper-V
        entries:
        - title: Ripristinare i carichi di lavoro Hyper-V
          url: "/br-use-hyperv-restore.html"
        - title: Ripristinare file e cartelle di Hyper-V
          url: "/br-use-hyper-v-restore-guest-files-and-folders.html"
    - title: Proteggi i carichi di lavoro Oracle Database (Preview)
      entries:
      - title: Panoramica sulla protezione dei carichi di lavoro del database Oracle
        url: "/br-use-oracle-protect-overview.html"
      - title: Scopri i carichi di lavoro Oracle Database
        url: "/br-start-discover-oracle.html"
      - title: Configurare un database Oracle
        url: "/br-start-configure-oracle-database.html"
      - title: Crea e gestisci gruppi di protezione per i carichi di lavoro Oracle
          Database
        url: "/br-use-oracle-protection-groups.html"
      - title: Creare e gestire le policy di backup dei carichi di lavoro di Oracle
          Database
        url: "/br-use-policies-oracle-create.html"
      - title: Esegui il backup dei carichi di lavoro Oracle Database
        url: "/br-use-oracle-backup.html"
      - title: Clona i carichi di lavoro del database Oracle
        url: "/br-use-oracle-clone.html"
      - title: Ripristina i carichi di lavoro del database Oracle
        url: "/br-use-oracle-restore.html"
      - title: Montare, smontare e catalogare i punti di ripristino
        url: "/br-use-oracle-mount-unmount.html"
    - title: Proteggere i carichi di lavoro di Kubernetes
      entries:
      - title: Panoramica sulla protezione dei carichi di lavoro di Kubernetes
        url: "/br-use-kubernetes-protect-overview.html"
      - title: Scopri i carichi di lavoro di Kubernetes
        url: "/br-start-discover-kubernetes.html"
      - title: Aggiungi e proteggi le applicazioni Kubernetes
        entries:
        - title: Aggiungi e proteggi le applicazioni Kubernetes
          url: "/br-use-protect-kubernetes-applications.html"
        - title: Creare e gestire le policy di backup dei carichi di lavoro Kubernetes
          url: "/br-use-policies-kubernetes-create.html"
        - title: Esegui subito il backup di un'applicazione Kubernetes utilizzando
            la web UI
          url: "/br-use-back-up-now-kubernetes-applications-web-ui.html"
        - title: Esegui subito il backup di un'applicazione Kubernetes utilizzando
            risorse personalizzate
          url: "/br-use-back-up-now-kubernetes-applications-cr.html"
      - title: Ripristina le applicazioni Kubernetes
        entries:
        - title: Ripristina le applicazioni Kubernetes utilizzando l'interfaccia utente
            web
          url: "/br-use-restore-kubernetes-applications.html"
        - title: Ripristina le applicazioni Kubernetes utilizzando risorse personalizzate
          url: "/br-use-restore-kubernetes-applications-cr.html"
        - title: Utilizza impostazioni avanzate di ripristino delle risorse personalizzate
          url: "/br-use-kubernetes-advanced-restore-settings.html"
        - title: Modifica le risorse durante le operazioni di ripristino utilizzando
            risorse personalizzate
          url: "/br-use-modify-resources-kubernetes-cr.html"
      - title: Gestire i cluster Kubernetes
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: Gestire le applicazioni Kubernetes
        url: "/br-use-manage-kubernetes-applications.html"
      - title: Gestisci i modelli di hook di esecuzione per i carichi di lavoro Kubernetes
        url: "/br-use-manage-execution-hook-templates.html"
      - title: Crea e gestisci report di protezione
        url: "/br-use-kubernetes-reports.html"
    - title: Monitorare i lavori
      url: "/br-use-monitor-tasks.html"
    - title: Riavvia NetApp Backup and Recovery
      url: "/reference-restart-backup.html"
    - title: Abilita anteprima e funzionalità nascoste
      url: "/enable-preview-features.html"
  - title: Automatizza con le API REST di NetApp Backup and Recovery
    url: "/br-api-backup-restore.html"
  - title: Riferimento
    entries:
    - title: Azioni di Backup and Recovery di NetApp verificate
      url: "/reference-audit-actions.html"
    - title: Criteri in SnapCenter confrontati con quelli in NetApp Backup and Recovery
      url: "/reference-policy-differences-snapcenter.html"
    - title: NetApp Backup and Recovery ruoli IAM
      url: "/reference-roles.html"
    - title: Ripristinare i dati di configurazione di NetApp Backup and Recovery in
        un sito oscuro
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Livelli di archiviazione AWS supportati con NetApp Backup and Recovery
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: Livelli di archiviazione Azure supportati con NetApp Backup and Recovery
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Livelli di archiviazione di Google Cloud supportati con NetApp Backup
        and Recovery
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
