---
sidebar: sidebar 
permalink: task-preview-enable.html 
keywords: cloud backup, NetApp Backup and Recovery, backup, restore, preview, enable, object storage, third-party, MinIO, S3-compatible 
summary: 'È possibile monitorare lo stato degli snapshot locali, delle repliche e dei backup nei processi di archiviazione degli oggetti avviati o pianificati, nonché ripristinare i processi avviati o pianificati.  È possibile visualizzare i lavori completati, quelli in corso o quelli falliti, in modo da poter diagnosticare e risolvere i problemi.  Utilizzando il Centro notifiche, puoi abilitare l"invio di notifiche tramite e-mail, così da essere informato sulle attività importanti del sistema anche quando non hai effettuato l"accesso al sistema.  Utilizzando la Timeline, puoi visualizzare i dettagli di tutte le azioni avviate tramite l"interfaccia utente o l"API.' 
---
= Abilita le funzionalità di anteprima in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery offre funzionalità di anteprima che consentono di testare le nuove funzionalità prima che vengano rilasciate definitivamente.  Queste funzionalità sono progettate per migliorare l'esperienza di backup e ripristino, ma potrebbero non essere completamente supportate o stabili.


IMPORTANT: Queste funzionalità sono in modalità di anteprima e non devono essere utilizzate in ambienti di produzione.  Sono destinati esclusivamente a scopo di test e feedback.



== Abilita le funzionalità di anteprima

Per abilitare le funzionalità di anteprima in NetApp Backup and Recovery, è necessario impostare un flag sull'agente Console.  Questo flag consente di accedere e testare le funzionalità di anteprima disponibili nel servizio.

.Passi
. Accedi all'agente Console.
. Passa al ruolo di Superutente.  Eseguire il comando:
+
`sudo su`

. Elenca i volumi Docker e identifica il volume CBS.  Eseguire il comando:
+
[listing]
----
podman volume ls | grep cbs
----
+
Risultati attesi:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. Ispezionare il volume per ottenere il punto di montaggio.  Eseguire il comando:
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
. Eseguire il comando:
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Risultati attesi:

+
[listing]
----
Mountpoint:
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Passare alla directory Docker Volumes.  Cambiare directory nel punto di montaggio ottenuto nel passaggio precedente:
+
[listing]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config

----
. Individuare e modificare il `production-customer.json` file.
. Assicurati di essere nella directory corretta e `production-customer.json` il file è presente.
. Apri il `production-customer.json` file nel tuo editor di testo preferito e aggiungi il seguente frammento JSON, assicurandoti che la struttura JSON sia mantenuta correttamente:
+
[listing]
----
{
   "feature-flags":
    {
        "volumes-dashboard-v2": true
     }
}
----
. Salvare le modifiche al file.
. Riavviare il servizio CBS NetApp Backup and Recovery Cloud Manager.  Eseguire il comando:
+
[listing]
----
podman restart cloudmanager_cbs
----

