---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Creare un certificato di sicurezza per abilitare la comunicazione tra NetApp Backup and Recovery e StorageGRID o ONTAP. 
---
= Configura i certificati CA per NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configura i certificati CA in modo che NetApp Backup and Recovery possa convalidare le connessioni sicure a StorageGRID o ONTAP. Segui i passaggi applicabili al tuo ambiente e ai sistemi che vuoi proteggere.



[[create-a-ca-certificate-for-storagegrid]]
== Crea un certificato CA per StorageGRID

Se la comunicazione tra i container di NetApp Backup and Recovery e StorageGRID deve verificare il certificato di StorageGRID, completa i seguenti passaggi.

Il certificato generato deve utilizzare lo stesso common name (CN) e lo stesso Subject Alternative Name che hai fornito in NetApp Backup and Recovery quando hai attivato il backup.

.Passi
. Per creare il certificato StorageGRID , seguire i passaggi indicati nella documentazione di StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Informazioni StorageGRID sulla configurazione dei certificati"]

. Aggiorna StorageGRID con il certificato se non lo hai già fatto.
. Accedi all'agente Console come utente root. Esegui:
+
[source, shell]
----
sudo su
----
. Individua il volume Docker di NetApp Backup and Recovery (Cloud Backup Service). Esegui:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Esempio di output:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: Il nome del volume varia tra le modalità di distribuzione Standard, Privata e Limitata. In questo esempio viene utilizzata la modalità Standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

. Trova il punto di montaggio del volume NetApp Backup and Recovery . Correre:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Esempio di output:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: Il punto di montaggio varia tra le modalità di distribuzione Standard, Privata e Limitata. Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

. Passare alla directory del punto di montaggio. Eseguire:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Se il certificato StorageGRID è firmato sia dalla root CA che da una CA intermedia, unisci entrambi i  `pem` file in un unico file chiamato  `sgws.crt` nella posizione corrente. Non aggiungere il certificato leaf a questo file.




[[steps-for-the-cloudmanagercbs-container]]
=== Passaggi per il container cloudmanager_cbs

Abilita la verifica del certificato del server StorageGRID in NetApp Backup and Recovery (Cloud Backup Service).

. Passa al volume Docker che hai trovato nei passaggi precedenti.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Passa alla directory di configurazione.
+
[source, shell]
----
cd cbs_config
----
. Crea e salva un file di configurazione come mostrato di seguito con uno dei seguenti nomi, in base al tuo ambiente di distribuzione:
+
** `production-customer.json` per le implementazioni in modalità Standard e modalità Restricted
** `darksite-customer.json` per le implementazioni in modalità privata
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

+
*File di configurazione*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Uscire dal contenitore. Correre:
+
[source, shell]
----
exit
----
. Ricomincia `cloudmanager_cbs` . Correre:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Passaggi per il container cloudmanager_cbs_catalog

Successivamente, abilita la verifica del certificato del server StorageGRID per il servizio di catalogazione.

. Passa al volume Docker:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configura il catalogo. Correre:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crea un file di configurazione come mostrato di seguito con uno dei seguenti nomi, in base al tuo ambiente di distribuzione:
+
** `production-customer.json` per le implementazioni in modalità Standard e modalità Restricted
** `darksite-customer.json` per le implementazioni in modalità privata
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

+
*File di configurazione del catalogo*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Riavvia il catalogo. Correre:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[update-the-console-agent-certificate-with-the-storagegrid-certificate-based-on-the-agent-operating-system]]
=== Aggiornare il certificato dell'agente della console con il certificato StorageGRID in base al sistema operativo dell'agente



==== Ubuntu

. Copia il certificato SGWS in  `/usr/local/share/ca-certificates`. Ecco un esempio:
+
[source, shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
Dove `sgws.crt` è il certificato CA radice.

. Aggiorna i certificati host con il certificato StorageGRID. Esegui:
+
[source, shell]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copia il certificato SGWS in `/etc/pki/ca-trust/source/anchors/` .
+
[source, shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
Dove `sgws.crt` è il certificato CA radice.

. Aggiornare i certificati host con il certificato StorageGRID .
+
[source, shell]
----
update-ca-trust extract
----
. Aggiorna il `ca-bundle.crt`
+
[source, shell]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Per verificare se i certificati sono presenti, eseguire il seguente comando:
+
[source, shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




[[create-a-ca-certificate-for-ontap]]
== Crea un certificato CA per ONTAP

Se la comunicazione tra i container NetApp Backup and Recovery e ONTAP deve convalidare il certificato ONTAP, completa i seguenti passaggi.

NetApp Backup and Recovery utilizza l'indirizzo IP di gestione del cluster per connettersi a ONTAP. Inserisci l'indirizzo IP del cluster nei campi Subject Alternative Name del certificato. Specifica questo valore quando generi la CSR in System Manager.

Utilizzare la documentazione di System Manager per creare un nuovo certificato CA per ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Gestisci i certificati con System Manager"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Come gestire i certificati SSL ONTAP con System Manager"]


.Passi
. Accedi all'agente Console come root. Esegui:
+
[source, shell]
----
sudo su
----
. Individua il volume Docker di NetApp Backup and Recovery. Esegui:
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Esempio di output:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: Il nome del volume varia tra le modalità di distribuzione Standard, Privata e Limitata. Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

. Individua il punto di montaggio del volume. Esegui:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Esempio di output:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: Il punto di montaggio varia tra le modalità di distribuzione Standard, Privata e Limitata. Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

. Passare alla directory del punto di montaggio. Eseguire:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Completa uno dei seguenti passaggi:
+
** Se il certificato ONTAP è firmato dalla CA radice e da una CA intermedia, aggiungere `pem` file di entrambi in un unico file denominato `ontap.crt` nella posizione attuale.
** Se il certificato ONTAP è firmato da una singola CA, rinominarlo `pem` archiviare come `ontap.crt` e copiarlo nella posizione corrente. Non aggiungere il certificato foglia a questo file.






[[steps-for-the-cloudmanagercbs-container]]
=== Passaggi per il container cloudmanager_cbs

Successivamente, abilita la verifica del certificato del server ONTAP in NetApp Backup and Recovery (Cloud Backup Service).

. Passa al volume Docker che hai trovato nei passaggi precedenti.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Passare alla directory config. Correre:
+
[source, shell]
----
cd cbs_config
----
. Crea un file di configurazione come mostrato di seguito con uno dei seguenti nomi, in base al tuo ambiente di distribuzione:
+
** `production-customer.json` per le implementazioni in modalità Standard e modalità Restricted
** `darksite-customer.json` per le implementazioni in modalità privata
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

+
*File di configurazione*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Uscire dal contenitore. Correre:
+
[source, shell]
----
exit
----
. Riavviare NetApp Backup and Recovery. Correre:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Passaggi per il container cloudmanager_cbs_catalog

Abilita la verifica del certificato del server ONTAP per il servizio di catalogazione.

. Passa al volume Docker. Esegui:
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Correre:
+
[source, shell]
----
cd cbs_catalog_config
----
. Crea un file di configurazione come mostrato di seguito con uno dei seguenti nomi, in base al tuo ambiente di distribuzione:
+
** `production-customer.json` per le implementazioni in modalità Standard e modalità Restricted
** `darksite-customer.json` per le implementazioni in modalità privata
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"] .

+
*File di configurazione*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Riavviare NetApp Backup and Recovery. Correre:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[create-a-certificate-for-both-ontap-and-storagegrid]]
== Creare un certificato sia per ONTAP che per StorageGRID

Se è necessario abilitare il certificato sia per ONTAP che per StorageGRID, il file di configurazione apparirà come segue:

*File di configurazione per ONTAP e StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----