---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Creare un certificato di sicurezza per abilitare la comunicazione tra NetApp Backup and Recovery e StorageGRID o ONTAP. 
---
= Impostare i certificati di sicurezza per StorageGRID e ONTAP in NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Creare un certificato di sicurezza per abilitare la comunicazione tra NetApp Backup and Recovery e StorageGRID o ONTAP.



== Creare un certificato di sicurezza per StorageGRID

Se la comunicazione tra i contenitori NetApp Backup and Recovery e StorageGRID deve verificare il certificato StorageGRID , completare i seguenti passaggi.

Il certificato generato deve avere CN e Subject Alternative Name come nome fornito in NetApp Backup and Recovery al momento dell'attivazione del backup.

.Passi
. Per creare il certificato StorageGRID , seguire i passaggi indicati nella documentazione di StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Informazioni StorageGRID sulla configurazione dei certificati"]

. Aggiorna StorageGRID con il certificato se non lo hai già fatto.
. Accedi all'agente Console come utente root.  Correre:
+
[source, console]
----
sudo su
----
. Ottieni il volume Docker NetApp Backup and Recovery (Cloud Backup Service).  Correre:
+
[source, console]
----
docker volume ls | grep cbs
----
+
Esempio di output:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: Il nome del volume varia tra le modalità di distribuzione Standard, Privata e Limitata.  In questo esempio viene utilizzata la modalità Standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

. Trova il punto di montaggio del volume NetApp Backup and Recovery .  Correre:
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Esempio di output:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: Il punto di montaggio varia tra le modalità di distribuzione Standard, Privata e Limitata.  Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

. Passare alla directory MountPoint.  Correre:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Se il certificato di StorageGRID è firmato dalla CA radice e da una CA intermedia, aggiungere `pem` file di entrambi in un unico file denominato `sgws.crt` nella posizione attuale.  Non aggiungere il certificato foglia a questo file.




=== Passaggi per il contenitore cloudmanager_cbs

Sarà necessario abilitare la verifica del certificato del server StorageGRID in NetApp Backup and Recovery (Cloud Backup Service).

. Passare alle directory del volume Docker ottenuto nei passaggi precedenti.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Cambiare directory e passare alla directory config.
+
[source, console]
----
cd cbs_config
----
. Crea e salva un file di configurazione come mostrato di seguito con uno dei seguenti nomi in base all'ambiente di distribuzione:
+
** `production-customer.json`Utilizzato per le distribuzioni in modalità Standard e in modalità Ristretta.
** `darksite-customer.json`Utilizzato per le distribuzioni in modalità privata.
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

+
*File di configurazione*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Uscire dal contenitore.  Correre:
+
[source, console]
----
exit
----
. Ricomincia `cloudmanager_cbs` .  Correre:
+
[source, console]
----
docker restart cloudmanager_cbs
----




=== Passaggi per il contenitore cloudmanager_cbs_catalog

Successivamente, sarà necessario abilitare la verifica del certificato del server StorageGRID per il servizio di catalogazione.

. Cambiare directory nel volume Docker:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configura il catalogo. Correre:
+
[source, console]
----
cd cbs_catalog_config
----
. Crea un file di configurazione come mostrato di seguito con uno dei seguenti nomi in base al tuo ambiente di distribuzione:
+
** `production-customer.json`Utilizzato per le distribuzioni in modalità Standard e in modalità Ristretta.
** `darksite-customer.json`Utilizzato per le distribuzioni in modalità privata.
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

+
*File di configurazione del catalogo*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Riavvia il catalogo.  Correre:
+
[source, console]
----
docker restart cloudmanager_cbs_catalog
----




=== Aggiornare il certificato dell'agente della console con il certificato StorageGRID in base al sistema operativo dell'agente



==== Ubuntu

. Copia il certificato SGWS in `/usr/local/share/ca-certificates` . Ecco un esempio:
+
[source, console]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
Dove `sgws.crt` è il certificato CA radice.

. Aggiornare i certificati host con il certificato StorageGRID . Correre
+
[source, console]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copia il certificato SGWS in `/etc/pki/ca-trust/source/anchors/` .
+
[source, console]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
Dove `sgws.crt` è il certificato CA radice.

. Aggiornare i certificati host con il certificato StorageGRID .
+
[source, console]
----
update-ca-trust extract
----
. Aggiorna il `ca-bundle.crt`
+
[source, console]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Per verificare se i certificati sono presenti, eseguire il seguente comando:
+
[source, console]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




== Creare un certificato di sicurezza per ONTAP

Se la comunicazione tra i contenitori NetApp Backup and Recovery e ONTAP deve convalidare il certificato ONTAP , completare i seguenti passaggi.

NetApp Backup and Recovery utilizza l'IP di gestione del cluster per connettersi a ONTAP.  Immettere l'indirizzo IP del cluster nei nomi alternativi dell'oggetto del certificato.  Specificare questo passaggio quando si genera la CSR tramite l'interfaccia utente di System Manager.

Utilizzare la documentazione di System Manager per creare un nuovo certificato CA per ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Gestisci i certificati con System Manager"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Come gestire i certificati SSL ONTAP con System Manager"]


.Passi
. Accedi all'agente della console come root.  Correre:
+
[source, console]
----
sudo su
----
. Ottieni il volume Docker NetApp Backup and Recovery .  Correre:
+
[source, console]
----
docker volume ls | grep cbs
----
+
Esempio di output:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: Il nome del volume varia tra le modalità di distribuzione Standard, Privata e Limitata.  Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

. Procuratevi il supporto per il volume.  Correre:
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Esempio di output:

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: Il punto di montaggio varia tra le modalità di distribuzione Standard, Privata e Limitata.  Questo esempio mostra una distribuzione cloud standard. Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

. Passare alla directory del punto di montaggio.  Correre:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Completa uno dei seguenti passaggi:
+
** Se il certificato ONTAP è firmato dalla CA radice e da una CA intermedia, aggiungere `pem` file di entrambi in un unico file denominato `ontap.crt` nella posizione attuale.
** Se il certificato ONTAP è firmato da una singola CA, rinominarlo `pem` archiviare come `ontap.crt` e copiarlo nella posizione corrente.  Non aggiungere il certificato foglia a questo file.






=== Passaggi per il contenitore cloudmanager_cbs

Successivamente, abilitare la verifica del certificato del server ONTAP in NetApp Backup and Recovery (Cloud Backup Service).

. Passare alle directory del volume Docker ottenuto nei passaggi precedenti.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Passare alla directory config.  Correre:
+
[source, console]
----
cd cbs_config
----
. Creare un file di configurazione come mostrato di seguito con uno dei seguenti nomi in base all'ambiente di distribuzione:
+
** `production-customer.json`Utilizzato per le distribuzioni in modalità Standard e in modalità Ristretta.
** `darksite-customer.json`Utilizzato per le distribuzioni in modalità privata.
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

+
*File di configurazione*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Uscire dal contenitore.  Correre:
+
[source, console]
----
exit
----
. Riavviare NetApp Backup and Recovery.  Correre:
+
[source, console]
----
docker restart cloudmanager_cbs
----




=== Passaggi per il contenitore cloudmanager_cbs_catalog

Abilitare la verifica del certificato del server ONTAP per il servizio di catalogazione.

. Passare alla directory del volume Docker.  Correre:
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Correre:
+
[source, console]
----
cd cbs_catalog_config
----
. Creare un file di configurazione come mostrato di seguito con uno dei seguenti nomi in base all'ambiente di distribuzione:
+
** `production-customer.json`Utilizzato per le distribuzioni in modalità Standard e in modalità Ristretta.
** `darksite-customer.json`Utilizzato per le distribuzioni in modalità privata.
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione della console NetApp"] .

+
*File di configurazione*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Riavviare NetApp Backup and Recovery.  Correre:
+
[source, console]
----
docker restart cloudmanager_cbs_catalog
----




== Creare un certificato sia per ONTAP che per StorageGRID

Se è necessario abilitare il certificato sia per ONTAP che per StorageGRID, il file di configurazione apparirà come segue:

*File di configurazione per ONTAP e StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----