= Ripristina volumi inferiori a 1 GB
:allow-uri-read: 




=== Ripristina volumi inferiori a 1 GB

Con questa versione, è ora possibile ripristinare i volumi creati in ONTAP di dimensioni inferiori a 1 GB.  La dimensione minima del volume che è possibile creare utilizzando ONTAP è di 20 MB.



=== Suggerimenti su come ridurre i costi di DataLock

La funzione DataLock protegge i file di backup da modifiche o eliminazioni per un periodo di tempo specificato.  Ciò è utile per proteggere i tuoi file dagli attacchi ransomware.

Per i dettagli su DataLock e suggerimenti su come mitigare i costi associati, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-policy-object-options.html["Impostazioni dei criteri di backup su oggetto"] .



=== Integrazione di AWS IAM Roles Anywhere

Il servizio Amazon Web Services (AWS) Identity and access Roles Anywhere consente di utilizzare ruoli IAM e credenziali a breve termine per i carichi di lavoro _all'esterno_ di AWS per accedere alle API AWS in modo sicuro, nello stesso modo in cui si utilizzano i ruoli IAM per i carichi di lavoro _su_ AWS.  Quando si utilizzano l'infrastruttura a chiave privata IAM Roles Anywhere e i token AWS, non sono necessarie chiavi di accesso AWS e chiavi segrete a lungo termine.  Ciò consente di ruotare le credenziali più frequentemente, migliorando la sicurezza.

Con questa versione, il supporto per il servizio AWS IAM Roles Anywhere è un'anteprima tecnologica.

Questo vale perlink:prev-ontap-backup-cvo-aws.html["backup di Cloud Volumes ONTAP su AWS"] .

Fare riferimento a https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog sulla versione NetApp Backup and Recovery di luglio 2024"] .



=== Ripristino della cartella o della directory FlexGroup ora disponibile

In precedenza, era possibile ripristinare i volumi FlexVol , ma non le cartelle o le directory FlexGroup .  Con ONTAP 9.15.1 p2, è possibile ripristinare le cartelle FlexGroup utilizzando l'opzione Sfoglia e ripristina.

Con questa versione, il supporto per il ripristino delle cartelle FlexGroup è un'anteprima tecnologica.

Per i dettagli, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["Ripristina cartelle e file utilizzando Sfoglia e Ripristina"] .

Per i dettagli su come abilitarlo manualmente, fare riferimento a https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog sulla versione NetApp Backup and Recovery di luglio 2024"] .
