= Esplorazione degli snapshot SMB
:allow-uri-read: 




=== Esplorazione degli snapshot SMB

Questo aggiornamento NetApp Backup and Recovery ha risolto un problema che impediva ai clienti di esplorare gli snapshot locali in un ambiente SMB.



=== Aggiornamento dell'ambiente AWS GovCloud

Questo aggiornamento NetApp Backup and Recovery ha risolto un problema che impediva all'interfaccia utente di connettersi a un ambiente AWS GovCloud a causa di errori del certificato TLS.  Il problema è stato risolto utilizzando il nome host dell'agente della console anziché l'indirizzo IP.



=== Limiti di conservazione della policy di backup

In precedenza, l'interfaccia utente NetApp Backup and Recovery limitava i backup a 999 copie, mentre la CLI ne consentiva di più.  Ora è possibile collegare fino a 4.000 volumi a un criterio di backup e includere 1.018 volumi non collegati a un criterio di backup.  Questo aggiornamento include ulteriori convalide che impediscono il superamento di questi limiti.



=== Risincronizzazione di SnapMirror Cloud

Questo aggiornamento garantisce che la risincronizzazione SnapMirror Cloud non possa essere avviata da NetApp Backup and Recovery per le versioni ONTAP non supportate dopo l'eliminazione di una relazione SnapMirror .
