= Miglioramento dei carichi di lavoro dei volumi ONTAP
:allow-uri-read: 




[[ontap-volumes-workloads-enhancement]]
=== Miglioramento dei carichi di lavoro dei volumi ONTAP

In questa versione, i carichi di lavoro ONTAP Volumes introducono il seguente miglioramento in anteprima:

*Supporto migliorato per i dark site*: NetApp Backup and Recovery per i dark site ora offre le stesse funzionalità di protezione dei dati di ONTAP Volumes di NetApp Backup and Recovery. Questo miglioramento include servizi aggiornati di backup, ripristino e gestione dei processi e un nuovo database di metadati. Durante un aggiornamento, i dati del database esistente vengono conservati e migrati automaticamente. Dopo l'aggiornamento, controlla i log di controllo per verificare che la migrazione sia stata completata correttamente. NetApp Backup and Recovery per i dark site supporta solo i carichi di lavoro ONTAP Volumes.

Per informazioni dettagliate sulla protezione dei carichi di lavoro di ONTAP Volumes, fare riferimento a  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Scopri la protezione dei volumi ONTAP con NetApp Backup and Recovery"].



[[kubernetes-workloads-enhancements]]
=== Miglioramenti dei carichi di lavoro Kubernetes

In questa versione, Kubernetes workloads introduce i seguenti miglioramenti:

* *Trident Protect 26.09*: Questa versione include Trident Protect 26.09.
* *Controllo degli accessi basato sui ruoli (RBAC) granulare a livello di cluster e namespace*: Durante la fase di rilevamento del cluster Kubernetes, puoi controllare l'accesso alle risorse selezionando un progetto o una cartella da associare al nuovo cluster. Puoi anche registrare namespace specifici per il controllo degli accessi. Questo consente un controllo degli accessi più granulare a livello di cluster o di namespace.
* *Ripristino di file e cartelle*: Ora puoi ripristinare o scaricare file e cartelle specifici dai backup delle applicazioni basate su macchine virtuali Kubernetes.


Per dettagli sulla protezione dei carichi di lavoro Kubernetes, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Scopri come proteggere i carichi di lavoro Kubernetes con NetApp Backup and Recovery"].
