= Creare un modello di hook di esecuzione
:allow-uri-read: 




== Creare un modello di hook di esecuzione

È possibile creare un modello di hook di esecuzione personalizzato da utilizzare per eseguire azioni prima o dopo un'operazione di protezione dei dati su un'applicazione.


NOTE: I modelli che crei qui sono utilizzabili solo quando proteggi i carichi di lavoro Kubernetes.

.Passi
. Nella Console, vai a *Protezione* > *Backup e ripristino*.
. Selezionare la scheda *Impostazioni*.
. Espandi la sezione *Modello di hook di esecuzione*.
. Selezionare *Crea modello di hook di esecuzione*.
. Immettere un nome per l'hook di esecuzione.
. Facoltativamente, scegli un tipo di hook. Ad esempio, un hook post-restore viene eseguito al termine dell'operazione di ripristino.
. Nella casella di testo *Script*, immettere lo script shell eseguibile che si desidera eseguire come parte del modello di hook di esecuzione.  Facoltativamente, puoi selezionare *Carica script* per caricare un file di script.
. Seleziona *Crea*.
+
Dopo aver creato il modello, questo viene visualizzato nell'elenco dei modelli nella sezione *Modello di hook di esecuzione*.


