= Annotazione del timeout dello spostamento dei dati
:allow-uri-read: 




== Annotazione del timeout dello spostamento dei dati

Utilizzare l'annotazione  `protect.trident.netapp.io/data-mover-timeout-sec` per impostare un timeout per-operazione del data mover (in secondi) durante backup e ripristino. Specifica per quanto tempo un data mover attende che un'operazione faccia progressi prima di andare in timeout. Questo è utile per rilevare e gestire trasferimenti bloccati (ad esempio, quando problemi di rete impediscono l'avanzamento del ripristino dei dati del volume).

Puoi utilizzare questa annotazione nel tuo file YAML come mostrato di seguito:

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
In questo esempio, l'annotazione fallisce l'operazione  `BackupRestore` se non si verifica alcun progresso entro 2 secondi nell'operazione di ripristino.


NOTE: Se il valore dell'annotazione è minore o uguale a 0, l'operazione fallirà immediatamente.
